const config = {
  name: "gonhay",
  aliases: ["n"],
  description: "",
  usage: "",
  cooldown: 3,
  permissions: [2],
  credits: "WaifuCat",
  extra: {
    list: [
       "Sủa Mau Lên🤣",
  "bố xin đái vào não tật mày nhé con chó",
  "Đĩ Má Mày Die",
  "sủa mạnh mẽ lên con lgbt ngu lồn",
  "mày hăng hái lên tí đc k",
  "Óc Chó🤭?",
  "sủa kìa",
  "mày biết sợ rồi à 🤣🤣?",
  "tao nói hồi sợ mày tự ái :(",
  "sợ mày bị tao sút đến die",
  "mày cố nữa đi 😂?",
  "clm 🤣?",
  "âm binh xuất trận à",
  "sát thương = 0 à",
  "Đã ngu còn thích tỏ ra mình có trình hả cn thú ngu êy",
  "Bởi vì mày làm gì có trình ?",
  "Thể hiện mình có trình đi con chó ngu ngục ơi ",
  "Sao mày sống mất dạy quá vậy bame mày khờ mà mày còn lười!",
  "Sủa hăng hái lên sao dị đú đa đú đỡn xạo lồn tập đú mxh ",
  "Lgbt xuất trận hả hay sao 🤔?",
  "Đừng cay cú cha mà hóa rồ lên làm nét ",
  "Nhìn lũ ngu dồn cha trong vô vọng kìa 😂",
  "Ráng đi sắp win r đó lũ đú êy",
  "Gần quin rồi ráng thêm sí nữa đi",
  "Đừng rụng nhé lũ ngu",
  "Trận này anh win rõ mà sao cưng chối ăng ẳng thế",
  "Khi nào con hết xàm lồn vậy?",
  "Sao con đú quá vậy con thú êy",
  "Alo con còn sống kh đó",
  "Hay bị hành quá nên sinh ra hoang tưởng ",
  "Mày sủa hăng hái lên cn thú đú eye",
  "Chậm chạp như rùa bò v",
  "Hăngg máu lên chứ yếu kém quá",
  "Gà mà hay xạo lồn quá vậy",
  "Cưng sủa lên đi sao im r ",
  "Cha cho im chưa hả cn thú ngu êy🤣",
  "Thấy cha là xách giò chạy hả",
  "Câm rồi à chán thế",
  "Mày nín r hả",
  "Sao nín r vậy",
  "Hay bị mẹ gank rồi",
  "Yếu kém quá cn thú ơi",
  "Hay đuối rồi jar",
  "Đuối r thì kêu cha cha tha cho",
  "Sao pải cuốn cuồng lên thế🤣",
  "Ai làm gì mà mếu r v",
  "Cay cú kh làm đc gì à",
  "Mếu máo rõ mà rồi sao nữa ht ngôn à ",
  "Yếu kém v thú đú nhảm lồn đú ửa kiểu",
  "Hay bị hành quá nên núp r",
  "Sao v mặt căng v cay cha rồi hả 🤨🌶?",
  "Cay cha rõ mà sao xạo lồn hả",
  "Nhìn mày gõ như đống tro tàn cốt mã nhà mày để lại cho mày vậy á",
  "Không được cay anh quá mà làm liều nghe chưa!",
  "Đừng bị anh chửi nhiều quá mà tự ái nhảy lầu tự tử nhé",
  "Đừng có lên mạng xã hội tạo nét mà bị anh hành là mếu máo đi cầu cứu ngay",
  "Khi nào có trình r đọ với anh chứ trình không có mà sủa hăng ghê ta ",
  "Cưng xạo lồn chứ làm gì có trình",
  "Rồi sao nữa",
  "Con điếm phò mã bị cha mày cầm cái cây chà bồn cầu cha chà nát lồn mày nè",
  "Con thú ngu dốt bị cha mày hành cho đầu óc quay cuồng r à",
  "Sao cay hả cay r làm được gì không hay chỉ được ngồi gõ nhảm bển 🌶",
  "Cay mếu máo sao khóc rồi",
  "Khóc r hả thương vậy",
  "Thương cho con thú cay anh mà không làm được gì",
  "Sao cho cầu cứu mà cầu cứu xog sao kh ai dám dô giúp ht vậy",
  "Sống chi bần hèn quá v",
  "Sao con đú mà con xạo lồn hả cn thú ngu êy",
  "Cha mày chuyên hành lũ đú mà",
  "Con sủa hăng máu lên ",
  "Câm là cha mày gọi hồn mày như gọi đò",
  "Con sơ hở là xạo lồn bịa chuyện ai xem",
  "Nhìn con dị hợm quá vậy?",
  "Con kiếp trước chắc sống phế lắm nhỉ",
  "Qua kiếp này làm lại từ đầu mà sao ngu quá v",
  "Cn thú cầm cái phím tắt ôm trong tuyệt vọng hả",
  "Đú sao lại được hả cn ngồi ôm phím gõ dăm ba mấy cái ngôn xưa lắc xưa lơ ",
  "Ai cứu mày được quả này",
  "Cầu cứu lẹ đi🤣",
  "Cha hóng nãy giờ nè🤣",
  "Mày mà câm là cha mày win rõ nhé",
  "Cha mày hóa thân thành hắc bạch vô thường cha mày bắt hồn đĩ mẹ mày xuống chầu diêm vương",
  "Con chó mày hăng hái lên xem nào",
  "Hay bị cha mày bón cho 1 kí hành dô mõm nên không dám sủa nữa",
  "cái thứ con người mà não còn không có mà đòi đọ với ai🤣",
  "Nhìn mặt mày như con tinh tinh đầu thai chuyển kiếp thành con người v🤣",
  "Nhìn mặt mày là thấy 2 chữ phèn ngu😗",
  "Đã nghèo đã phèn đã ngu đã dốt mà đòi hơn ai",
  "Bản thân mình không làm được cho mình thì làm được cho ai",
  "Sống như 1 con chó ngu dốt như lũ phèn ói chợ búa cầm dao múa kiếm",
  "Sủa hăng hái lên chứ yếu kém quá cha mày hăng không nổi😉!",
  "Gõ phím tắt để làm nét ai xem",
  "Mày đi cầu cứu ai hả!?",
  "Tao đố đứa nào dám dô cứu mày đấy",
  "Đã ngu còn hay tạo nét",
  "Cha mày tới là lũ ngu cũm pải dè chừng",
  "Đã ngu còn đú thì phế mẹ đi",
  "Cha đấng mxh mà🤔!",
  "Cưng ganh tị với anh hả?",
  "Cưng hăng hái với ai?",
  "Sao con đuối rồi hả?",
  "Chỉ được vậy thôi hả!",
  "Còn chiêu nào không tung ra đi",
  "Chứ thấy mấy cái chiêu trò phèn của mày đi trong ruột mày từ 7 kiếp r ",
  "Bị cha mày hành nhiều quá nên sính ra hoa tưởng hả 🤨?!",
  "Con sống ngu mà con hay tạo nét quá v cn thú ngu êy",
  "Con thú ngu bị cha mày hành nhìu quá nên không dám sủa nữa à",
  "Sao vậy yếu kém vậy hay đuối r hả đĩ gà mờ",
  "Cha mày tới là lũ ngu cũm pải rén mà thôi", 
  "Hăng lên xíu được không dọ",
  "Nín hết rồi hả sao không hăng như ban đầu đê",
  "Sao mấy cn thú đi theo bầy đàn bị cha mày hành tới mức mà pải núp hết rồi dị",
  "Não mày bị chèn tinh trùng của thằng cha mày trổng hả?",
  "Não tàn đến mức pải đi xin tha hả?",
  "Não mày chứa toàn cứt của con chó nhà mày à",
  "Sao mày không hăng hái nữa",
  "Hay rớt rồi hả",
  "Sao câm nín rồi 😑",
  "Sủa hăng hái máu chiến lên nào",
  "Yếu kém v con thú đú ngu êy",
  "Sủa sao cho nghe lọt lỗ tai",
  "Cha tới nè nhú lên diện kiến cha lẹ",
  "Bame mày quỳ lạy kêu anh xin tha mà",
  "Cốt cách như buồi gõ xàm gõ điên",
  "Gõ sao lại tụi anh được hả lũ đú ",
  "Đã ngu còn thích sỉ diện",
  "Chó ngoan cục cưng hãy về với chủ đừng cắn bậy",
  "Sống sang lên cho nết thanh tịnh",
  "Sống dơ sồng hèn muôn đời bết",
  "Còn sống thì nhú lên đú tiếp cho tụi anh chiêm ngưỡng",
  "Tàn tạ từ nhân cách đến não bộ",
  "Sống cho cuộc đời có tâm và có tầm",
  "Ngu thì đừng phán vs ai nhé cn chó ghẻ ",
  "Nghe 1 thời giảng sanh của cha mà tích đức",
  "Sống như con chó ngu dốt đầu đường xó chợ",
  "Ngồi xuống cha giảng đạo cho nghe nè",
  "Nghèo bần hèn bị cha mày đứng trên đạp đầu lũ đú chúng mày cha đi lên ",
  "Cay mếu máo cha mà chả làm được gì hả",
  "Không được quay qua méc mẹ nghe chưa",
  "Đã ngu còn thích thể hiện hả thk nhóc",
  "Khi nào đủ trình r so với anh nghe chưa",
  "Thân phận nghèo hèn đú ai xem ",
  "Đú má mày tới tháng xịt nước máu kinh cho thk cha mày uống",
  "Khi nào con có đủ tầm ảnh hưởng lên đứng với cha ",
  "ê wavy giả bộ ngừng đi",
  "Gõ ngôn lặp đi lặp lại ngôn 1 màu thì đừng gõ",
  "Thứ yêu nghiệt xuống hạn nhân sanh",
  "Sủa dơ cha mày cầm cái chổi nhét dô lồn m nè",
  "Thứ súc sinh muốn tiến hóa thành người",
  "Mày ngưng là má mày đột tử tới",
  "Thú đú như mày làm cha bùn cười quá ",
  "Khi nào có trình đú với anh nha",
  "Sao chậm quá vậy?😂",
  "Sủa hăng hái mạnh mẽ lên",
  "Cốt cách thiên nga tâm hồn quỷ dữ 😈",
  "sủa mau lên con chó🤣🤣",
  "con đĩ cave lộ lồn cay kiểu🤣🤣",
  "lũ ngu đòi đọ bot anh🤣👉",
  "kkk🤣🤣",
  "con đĩ cave show lồn show dú kiểu😜",
  "mày sợ anh à con đĩ😏?",
  "xạo à clm cuoii😏?",
  "sao m xạo da👉",
"cố đeee🤭",
"sồn hăng lên em🥺",
  "lên nhây cái em êi",
"m lết mặt thú m lên nhây đê",
"sồn như chó cắn v",
"nhanh đi thg óc heo",
"não tép à",
"sao vậy ",
"chửi nhau hăng đi ",
"làm tí nhây",
"cố gắng xíuuuu",
"đc kh đó",
"thấy m chậm vãi l",
"cần anh chiêu mộ cho m ko đĩ",
"đáp ngôn nhanh hơn tý đc k tk ngu xuẩn🌬",
"m ớt cha hả🌶",
"m sợ cha đến v à",
"đụ má thg lồn mồ côi",
"cãi cùn lmj",
"m bại à",
"mày còn trò gì hay k",
"nhai lmjz tr",
"kh đc méc mẹ nè",
"câm à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"sao m yếu v😔",
"cố tí nữa👉",
"sao kìa chậm à🙃",
"hăng hái lên tí chứ😤",
"tới sáng đi em ei=))",
"cố gắng tí eii🤑",
"k đc à:))",
"con eii cố de😗",
"sao m câm kì:))",
"gà j🤭",
"tnh gà=))",
"m gà mà🤨",
"dk à:)?",
"đúng mà ?",
"cãi à :))",
"mày còn gì khác hơn không :))",
"học lỏm kìa🤣",
"cố tí e ?",
"mếu à😭",
"sao mếu kìa:))",
"tao đã cho m mếu đâu :))",
"va lẹ lên chậm v😏?",
"sao kìa",
"từ bỏ r à",
"bị bạn bè bỏ rơi à 😏?",
"mạnh mẽ tí đi nà",
"cố đê con chó ăn cứt:))?",
":)))",
"sợ tao kìa🤣",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố eiii",
"hăng tiếp đi",
"tới sáng k em",
"ko tới sáng à",
"chán v",
"m gà vậy :))",
"sao ngu dậy con:))",
"coi tụi nó dồn ngu kìa",
"sao mày ngu dậy:))?",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới nhiêu đó đã đuối r à:))?",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận ae eii",
"thg cặc giết cha mắng mẹ",
"sủa mạnh đê",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à🤣🤣",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"sao lại chạy vậy😏?",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"sủa cháy đê",
"sủa mạnh eei",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi à",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi",
  "bị chửi nên không phản kháng à",
  "con cave và tk cu bé hợp nhề😏",
  "con bede không phản kháng được à",
  "con bede sợ anh rồi:)",
  "chạy về mách mẹ à con bede",
  "chạy về trốn dô cái lồn mẹ mày đi?",
  "1 đứa bú lồn mẹ",
  "1 đứa bú cu cha",
  "bất hiếu cmnr:))",
  "mày làm gì để anh sợ đi:))",
  "mày có tý sát thương nào ko",
  "con đĩ mẹ mày ăn cứt cố đi",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm",
  "lũ cave cay cha cmnr",
  "cay anh  r à lũ đú",
  "sợ anh  à",
  "anh  win m mà:)))",
  "win nha clm bede🤣🤣",
  "sủa đi",
"cố lên con",
"sồn hăng lên em",
"sao m yếu v ",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em=))",
"cố gắng tí con chó dốt=))",
"k đc à",
"con chó ngu cố đê",
"sao m câm kìa",
"gà j",
"mày sợ anh à =))",
"m gà mà",
"mày ngu rõ mà",
"đúng mà",
"cãi à",
"mày còn gì khác k",
"học lỏm kìa",
"cố tí em",
"mếu à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"va lẹ đi con dốt",
"sao kìa",
"từ bỏ r à",
"mạnh mẽ tí đi con đĩ",
"cố lên con chó ngu",
"=)) cay tao à con đĩ",
"sợ tao à",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố lên chó dốt",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"m gà mà",
"log acc thay phiên à",
"coi tụi nó dồn ngu kìa",
"sợ tao à con chó đần",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới 5p đã câm r",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
   "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi sao",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi🥺?",
  "bị chửi nên không phản kháng à😀?",
  "con cave và tk cu bé hợp nhề😏👉",
  "2 con bede không phản kháng được à😋",
  "2 con bede sợ anh rồi:))🙃",
  "chạy về mách mẹ à 2 con bede😗?",
  "chạy về trốn dô cái lồn mẹ mày đi😍?",
  "1 đứa bú lồn mẹ😎?",
  "1 đứa bú cu cha😎?",
  "bất hiếu cmnr:))😜",
  "mày làm gì để anh sợ đi:))🤣?",
  "mày có tý sát thương nào ko😂?",
  "con đĩ mẹ mày ăn cứt cố đi🤣?",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm🤣",
  "lũ cave cay cha cmnr😑",
  "cay cha r à lũ đú😅",
  "sợ anh tao rồi à😗",
  "anh  win m mà:)))",
  "win nha clm bede🤣🤣",
   "con eii",
"cố đeee",
"sồn hăng lên em",
"sao m yếu v",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em eii",
"cố gắng tí eii",
"k đc à",
"con eii cố de",
"sao m câm kìa",
"gà j",
"tnh gà",
"m gà mà",
"dk à",
"đúng mà",
"cãi à",
"mày còn gì khác k",
"học lỏm kìa",
"cố tí em",
"mếu à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"va lẹ eii",
"sao kìa",
"từ bỏ r à",
"mạnh mẽ tí đi nà",
"cố eii",
":)))",
"sợ tao à",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố eiii",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"m gà mà",
"log acc thay phiên à",
"coi tụi nó dồn ngu kìa",
"ae ơiii",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới 5p đã câm r",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận ae eii",
"thg cặc giết cha mắng mẹ",
"sủa mạnh eii",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"sủa cháy đê",
"sủa mạnh eei",
"hăng lên đeeee",
"sồn hăng lên em",
"thấy m yếu ",
"cố tí nha",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em eii",
"cố gắng tí nữa sắp win r á",
"kh đc à hay sao v",
"con eii cố lên",
"sao m câm kìa",
      "sủa đi",
      "cố lên con",
      "sồn hăng lên em",
      "sao m yếu v ",
      "cố tí nữa",
      "sao kìa chậm à",
      "hăng hái lên tí chứ",
      "tới sáng đi em=))",
      "cố gắng tí con chó dốt=))",
      "k đc à",
      "con chó ngu cố đê",
      "sao m câm kìa",
      "gà j",
      "mày sợ anh à =))",
      "m gà mà",
      "mày ngu rõ mà",
      "đúng mà",
      "cãi à",
      "mày còn gì khác k",
      "học lỏm kìa",
      "cố tí em",
      "mếu à",
      "sao mếu kìa",
      "tao đã cho m mếu đâu",
      "va lẹ đi con dốt",
      "sao kìa",
      "từ bỏ r à",
      "mạnh mẽ tí đi con đĩ",
      "cố lên con chó ngu",
      "=)) cay tao à con đĩ",
      "sợ tao à",
      "sao sợ tao kìa",
      "cay lắm phải kh",
      "ớt rồi kìa em",
      "mày còn chối à",
      "làm tí đê",
      "mới đó đã mệt r kìa",
      "sao gà mà sồn v",
      "sồn như lúc đầu cho tao",
      "sao à",
      "ai cho m nhai",
      "cay lắm r",
      "từ bỏ đi em",
      "mày nghĩ mày làm t cay đc à",
      "có đâu",
      "tao đang hành m mà",
      "bịa à",
      "cay :)))))",
      "cố lên chó dốt",
      "hăng tiếp đi",
      "tới sáng k em",
      "k tới sáng à",
      "chán v",
      "m gà mà",
      "log acc thay phiên à",
      "coi tụi nó dồn ngu kìa",
      "sợ tao à con chó đần",
      "lại win à",
      "lại win r",
      "lũ cặc cay tao lắm🤣🤣",
      "cố lên đê",
      "sao mới 5p đã câm r",
      "yếu đến thế à",
      "sao kìa",
      "khóc kìa",
      "cầu cứu lẹ ei",
      "ai cứu đc m à :))",
      "tao bá mà",
      "sao m gà thế",
      "hăng lẹ cho tao",
      "con chó eiii🤣",
      "ổn k em",
      "kh ổn r à",
      "mày óc à con chó bẻm=))",
      "mẹ mày ngu à",
      "bú cặc cha m k em",
      "thg giả gái :))",
      "coi nó ngu kìa ae",
      "con chó này giả ngu à",
      "m ổn k",
      "mồ côi kìa",
      "sao v sợ r à",
      "cố gắng tí em",
      "cay cú lắm r",
      "đấy đấy bắt đầu",
      "chảy nước đái bò r à em",
      "sao kìa đừng run",
      "mày run à:))",
      "thg dái lở",
      "cay mẹ m lắm",
      "lgbt xuất trận à con đĩ",
      "thg cặc giết cha mắng mẹ",
      "sủa mạnh eii",
      "mày chết r à:))",
      "sao chết kìa",
      "bị t hành nên muốn chết à",
      "con lồn ngu=))",
      "sao kìa",
      "mạnh lên kìa",
      "yếu sinh lý à",
      "sủa đê",
      "cay à",
      "hăng đê",
      "gà kìa ae",
      "akakaa",
      "óc chó kìa",
      "🤣🤣🤣",
      "ổn không🤣🤣",
      "bất ổn à",
      "ơ kìaaa",
      "hăng hái đê",
      "chạy à 🤣🤣",
      "tởn à",
      "kkkk",
      "mày dốt à",
      "cặc ngu",
      "cháy đê",
      "chat hăng lên",
      "cố lên",
      "mồ côi cay",
      "cay à",
      "cn chó ngu",
      "óc cặc kìa",
      "đĩ đú:))",
      "đú kìa",
      "cùn v",
      "r x",
      "hhhhh",
      "kkakak",
      "sao đú",
      "cặc con",
      "ngu kìa",
      "chat mạnh đê",
      "hăng ee",
      "ơ ơ ơ",
      "sủa cháy đê",
      "sủa mạnh eei",
      "mày óc à con",
      "tao cho m chạy à",
      "con đĩ ngu sủa?",
      "mày chạy à con đĩ lồn",
    ]
  }
};



let index = 0;
let isStopped = false;

export function Running( {
  message,extra
}) {
  const {list} = extra;
  const args = message.body.split(" ").slice(1);
  if (args[0] === "stop") {
    isStopped = true;
    message.send("alo");
    return;
  }

  if (isStopped) {
    isStopped = false;
  }

  const sendText = () => {
    message.send(list[index]);
    index = (index + 1) % list.length;
    if (!isStopped) {
      setTimeout(sendText, 2000);
    }
  };
  sendText();
}

export default {
  config,
  Running
};
