const config = {
  name: "gonhay",
  aliases: ["n"],
  description: "",
  usage: "",
  cooldown: 3,
  permissions: [2],
  credits: "WaifuCat",
  extra: {
    list: [
        "cha đến nè bọn ngu 😂",
  "Lũ đú hết thời lên đây xưng danh với ai",
   "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
   "Sủa Mau Lên🤣",
    "bố xin đái vào não tật mày nhé con chó",
    "Đĩ Má Mày Die",
    "sủa mạnh mẽ lên con lgbt ngu lồn",
    "mày hăng hái lên tí đc k",
    "Óc Chó🤭?",
    "sủa kìa",
    "mày biết sợ rồi à 🤣🤣?",
    "tao nói hồi sợ mày tự ái :(",
    "sợ mày bị tao sút đến die",
    "mày cố nữa đi 😂?",
    "clm 🤣?",
  "Đã ngu còn thích tỏ ra mình có trình hả cn thú ngu êy",
  "Bởi vì mày làm gì có trình ?",
  "Thể hiện mình có trình đi con chó ngu ngục ơi ",
  "Sao mày sống mất dạy quá vậy bame mày khờ mà mày còn lười!",
  "Sủa hăng hái lên sao dị đú đa đú đỡn xạo lồn tập đú mxh ",
  "Lgbt xuất trận hả hay sao 🤔?",
  "Đừng cay cú cha mà hóa rồ lên làm nét ",
  "Nhìn lũ ngu dồn cha trong vô vọng kìa 😂",
  "Ráng đi sắp win r đó lũ đú êy",
  "Gần quin rồi ráng thêm sí nữa đi",
  "Đừng rụng nhé lũ ngu",
  "Trận này anh win rõ mà sao cưng chối ăng ẳng thế",
  "Khi nào con hết xàm lồn vậy?",
  "Sao con đú quá vậy con thú êy",
  "Alo con còn sống kh đó",
  "Hay bị hành quá nên sinh ra hoang tưởng ",
  "Mày sủa hăng hái lên cn thú đú eye",
  "Chậm chạp như rùa bò v",
  "Hăngg máu lên chứ yếu kém quá",
  "Gà mà hay xạo lồn quá vậy",
  "Cưng sủa lên đi sao im r ",
  "Cha cho im chưa hả cn thú ngu êy🤣",
  "Thấy cha là xách giò chạy hả",
  "Câm rồi à chán thế",
  "Mày nín r hả",
  "Sao nín r vậy",
  "Hay bị mẹ gank rồi",
  "Yếu kém quá cn thú ơi",
  "Hay đuối rồi jar",
  "Đuối r thì kêu cha cha tha cho",
  "Sao pải cuốn cuồng lên thế🤣",
  "Ai làm gì mà mếu r v",
  "Cay cú kh làm đc gì à",
  "Mếu máo rõ mà rồi sao nữa ht ngôn à ",
  "Yếu kém v thú đú nhảm lồn đú ửa kiểu",
  "Hay bị hành quá nên núp r",
  "Sao v mặt căng v cay cha rồi hả 🤨🌶?",
  "Cay cha rõ mà sao xạo lồn hả",
  "Nhìn mày gõ như đống tro tàn cốt mã nhà mày để lại cho mày vậy á",
  "Không được cay anh quá mà làm liều nghe chưa!",
  "Đừng bị anh chửi nhiều quá mà tự ái nhảy lầu tự tử nhé",
  "Đừng có lên mạng xã hội tạo nét mà bị anh hành là mếu máo đi cầu cứu ngay",
  "Khi nào có trình r đọ với anh chứ trình không có mà sủa hăng ghê ta ",
  "Cưng xạo lồn chứ làm gì có trình",
  "Rồi sao nữa",
  "Con điếm phò mã bị cha mày cầm cái cây chà bồn cầu cha chà nát lồn mày nè",
  "Con thú ngu dốt bị cha mày hành cho đầu óc quay cuồng r à",
  "Sao cay hả cay r làm được gì không hay chỉ được ngồi gõ nhảm bển 🌶",
  "Cay mếu máo sao khóc rồi",
  "Khóc r hả thương vậy",
  "Thương cho con thú cay anh mà không làm được gì",
  "Sao cho cầu cứu mà cầu cứu xog sao kh ai dám dô giúp ht vậy",
  "Sống chi bần hèn quá v",
  "Sao con đú mà con xạo lồn hả cn thú ngu êy",
  "Cha mày chuyên hành lũ đú mà",
  "Con sủa hăng máu lên ",
  "Câm là cha mày gọi hồn mày như gọi đò",
  "Con sơ hở là xạo lồn bịa chuyện ai xem",
  "Nhìn con dị hợm quá vậy?",
  "Con kiếp trước chắc sống phế lắm nhỉ",
  "Qua kiếp này làm lại từ đầu mà sao ngu quá v",
  "Cn thú cầm cái phím tắt ôm trong tuyệt vọng hả",
  "Đú sao lại được hả cn ngồi ôm phím gõ dăm ba mấy cái ngôn xưa lắc xưa lơ ",
  "Ai cứu mày được quả này",
  "Cầu cứu lẹ đi🤣",
  "Cha hóng nãy giờ nè🤣",
  "Mày mà câm là cha mày win rõ nhé",
  "Cha mày hóa thân thành hắc bạch vô thường cha mày bắt hồn đĩ mẹ mày xuống chầu diêm vương",
  "Con chó mày hăng hái lên xem nào",
  "Hay bị cha mày bón cho 1 kí hành dô mõm nên không dám sủa nữa",
  "cái thứ con người mà não còn không có mà đòi đọ với ai🤣",
  "Nhìn mặt mày như con tinh tinh đầu thai chuyển kiếp thành con người v🤣",
  "Nhìn mặt mày là thấy 2 chữ phèn ngu😗",
  "Đã nghèo đã phèn đã ngu đã dốt mà đòi hơn ai",
  "Bản thân mình không làm được cho mình thì làm được cho ai",
  "Sống như 1 con chó ngu dốt như lũ phèn ói chợ búa cầm dao múa kiếm",
  "Sủa hăng hái lên chứ yếu kém quá cha mày hăng không nổi😉!",
  "Gõ phím tắt để làm nét ai xem",
  "Mày đi cầu cứu ai hả!?",
  "Tao đố đứa nào dám dô cứu mày đấy",
  "Đã ngu còn hay tạo nét",
  "Cha mày tới là lũ ngu cũm pải dè chừng",
  "Đã ngu còn đú thì phế mẹ đi",
  "Cha đấng mxh mà🤔!",
  "Cưng ganh tị với anh hả?",
  "Cưng hăng hái với ai?",
  "Sao con đuối rồi hả?",
  "Chỉ được vậy thôi hả!",
  "Còn chiêu nào không tung ra đi",
  "Chứ thấy mấy cái chiêu trò phèn của mày đi trong ruột mày từ 7 kiếp r ",
  "Bị cha mày hành nhiều quá nên sính ra hoa tưởng hả 🤨?!",
  "Con sống ngu mà con hay tạo nét quá v cn thú ngu êy",
  "Con thú ngu bị cha mày hành nhìu quá nên không dám sủa nữa à",
  "Sao vậy yếu kém vậy hay đuối r hả đĩ gà mờ",
  "Cha mày tới là lũ ngu cũm pải rén mà thôi", 
  "Hăng lên xíu được không dọ",
  "Nín hết rồi hả sao không hăng như ban đầu đê",
  "Sao mấy cn thú đi theo bầy đàn bị cha mày hành tới mức mà pải núp hết rồi dị",
  "Não mày bị chèn tinh trùng của thằng cha mày trổng hả?",
  "Não tàn đến mức pải đi xin tha hả?",
  "Não mày chứa toàn cứt của con chó nhà mày à",
  "Sao mày không hăng hái nữa",
  "Hay rớt rồi hả",
  "Sao câm nín rồi 😑",
  "Sủa hăng hái máu chiến lên nào",
  "Yếu kém v con thú đú ngu êy",
  "Sủa sao cho nghe lọt lỗ tai",
  "Cha tới nè nhú lên diện kiến cha lẹ",
  "Bame mày quỳ lạy kêu anh xin tha mà",
  "Cốt cách như buồi gõ xàm gõ điên",
  "Gõ sao lại tụi anh được hả lũ đú ",
  "Đã ngu còn thích sỉ diện",
  "Chó ngoan cục cưng hãy về với chủ đừng cắn bậy",
  "Sống sang lên cho nết thanh tịnh",
  "Sống dơ sồng hèn muôn đời bết",
  "Còn sống thì nhú lên đú tiếp cho tụi anh chiêm ngưỡng",
  "Tàn tạ từ nhân cách đến não bộ",
  "Sống cho cuộc đời có tâm và có tầm",
  "Ngu thì đừng phán vs ai nhé cn chó ghẻ ",
  "Nghe 1 thời giảng sanh của cha mà tích đức",
  "Sống như con chó ngu dốt đầu đường xó chợ",
  "Ngồi xuống cha giảng đạo cho nghe nè",
  "Nghèo bần hèn bị cha mày đứng trên đạp đầu lũ đú chúng mày cha đi lên ",
  "Cay mếu máo cha mà chả làm được gì hả",
  "Không được quay qua méc mẹ nghe chưa",
  "Đã ngu còn thích thể hiện hả thk nhóc",
  "Khi nào đủ trình r so với anh nghe chưa",
  "Thân phận nghèo hèn đú ai xem ",
  "Đú má mày tới tháng xịt nước máu kinh cho thk cha mày uống",
  "Khi nào con có đủ tầm ảnh hưởng lên đứng với cha ",
  "ê wavy giả bộ ngừng đi",
  "Gõ ngôn lặp đi lặp lại ngôn 1 màu thì đừng gõ",
  "Thứ yêu nghiệt xuống hạn nhân sanh",
  "Sủa dơ cha mày cầm cái chổi nhét dô lồn m nè",
  "Thứ súc sinh muốn tiến hóa thành người",
  "Mày ngưng là má mày đột tử tới",
  "Thú đú như mày làm cha bùn cười quá ",
  "Khi nào có trình đú với anh nha",
  "Sao chậm quá vậy?😂",
  "Sủa hăng hái mạnh mẽ lên",
  "Cốt cách thiên nga tâm hồn quỷ dữ 😈",
    "âm binh xuất trận à",
    "sát thương = 0 à",
    "sủa mau lên con chó🤣🤣",
    "con đĩ cave lộ lồn cay kiểu🤣🤣",
    "lũ ngu đòi đọ bot anh🤣👉",
    "kkk🤣🤣",
    "con đĩ cave show lồn show dú kiểu😜",
    "mày sợ anh à con đĩ😏?",
    "xạo à clm cuoii😏?",
    "sao m xạo da👉",
  "cố đeee🤭",
  "sồn hăng lên em🥺",
    "lên nhây cái em êi",
  "m lết mặt thú m lên nhây đê",
  "sồn như chó cắn v",
  "nhanh đi thg óc heo",
  "não tép à",
  "sao vậy ",
  "chửi nhau hăng đi ",
  "làm tí nhây",
  "cố gắng xíuuuu",
  "đc kh đó",
  "thấy m chậm vãi l",
  "cần anh chiêu mộ cho m ko đĩ",
  "đáp ngôn nhanh hơn tý đc k tk ngu xuẩn🌬",
  "m ớt cha hả🌶",
  "m sợ cha đến v à",
  "đụ má thg lồn mồ côi",
  "cãi cùn lmj",
  "m bại à",
  "mày còn trò gì hay k",
  "nhai lmjz tr",
  "kh đc méc mẹ nè",
  "câm à",
  "sao mếu kìa",
  "tao đã cho m mếu đâu",
  "sao m yếu v😔",
  "cố tí nữa👉",
  "sao kìa chậm à🙃",
  "hăng hái lên tí chứ😤",
  "tới sáng đi em ei=))",
  "cố gắng tí eii🤑",
  "k đc à:))",
  "con eii cố de😗",
  "sao m câm kì:))",
  "gà j🤭",
  "tnh gà=))",
  "m gà mà🤨",
  "dk à:)?",
  "đúng mà ?",
  "cãi à :))",
  "mày còn gì khác hơn không :))",
  "học lỏm kìa🤣",
  "cố tí e ?",
  "mếu à😭",
  "sao mếu kìa:))",
  "tao đã cho m mếu đâu :))",
  "va lẹ lên chậm v😏?",
  "sao kìa",
  "từ bỏ r à",
  "bị bạn bè bỏ rơi à 😏?",
  "mạnh mẽ tí đi nà",
  "cố đê con chó ăn cứt:))?",
  ":)))",
  "sợ tao kìa🤣",
  "sao sợ tao kìa",
  "cay lắm phải kh",
  "ớt rồi kìa em",
  "mày còn chối à",
  "làm tí đê",
  "mới đó đã mệt r kìa",
  "sao gà mà sồn v",
  "sồn như lúc đầu cho tao",
  "sao à",
  "ai cho m nhai",
  "cay lắm r", 
  "từ bỏ đi em",
  "mày nghĩ mày làm t cay đc à",
  "có đâu",
  "tao đang hành m mà",
  "bịa à",
  "cay :)))))",
  "cố eiii",
  "hăng tiếp đi",
  "tới sáng k em",
  "ko tới sáng à",
  "chán v",
  "m gà vậy :))",
  "sao ngu dậy con:))",
  "coi tụi nó dồn ngu kìa",
  "sao mày ngu dậy:))?",
  "lại win à",
  "lại win r",
  "lũ cặc cay tao lắm🤣🤣",
  "cố lên đê",
  "sao mới nhiêu đó đã đuối r à:))?",
  "yếu đến thế à",
  "sao kìa",
  "khóc kìa",
  "cầu cứu lẹ ei",
  "ai cứu đc m à :))",
  "tao bá mà",
  "sao m gà thế",
  "hăng lẹ cho tao",
  "con chó eiii🤣",
  "ổn k em",
  "kh ổn r à",
  "xin tha eii",
  "mẹ mày ngu à",
  "bú cặc cha m k em",
  "thg giả gái :))",
  "coi nó ngu kìa ae",
  "con chó này giả ngu à",
  "m ổn k",
  "mồ côi kìa",
  "sao v sợ r à",
  "cố gắng tí em",
  "cay cú lắm r",
  "đấy đấy bắt đầu",
  "chảy nước đái bò r à em",
  "sao kìa đừng run",
  "mày run à:))",
  "thg dái lở",
  "cay mẹ m lắm",
  "lgbt xuất trận ae eii",
  "thg cặc giết cha mắng mẹ",
  "sủa mạnh đê",
  "mày chết r à:))",
  "sao chết kìa",
  "bị t hành nên muốn chết à🤣🤣",
  "con lồn ngu=))",
  "sao kìa",
  "mạnh lên kìa",
  "yếu sinh lý à",
    "sủa đê",
  "cay à",
  "hăng đê",
  "gà kìa ae",
  "akakaa",
  "óc chó kìa",
  "🤣🤣🤣",
  "ổn không🤣🤣",
  "bất ổn à",
  "ơ kìaaa",
  "sao lại chạy vậy😏?",
  "hăng hái đê",
  "chạy à 🤣🤣",
  "tởn à",
  "kkkk",
  "mày dốt à",
  "cặc ngu",
  "cháy đê",
  "chat hăng lên",
  "cố lên",
  "mồ côi cay",
  "cay à",
  "cn chó ngu",
  "óc cặc kìa",
  "đĩ đú:))",
  "đú kìa",
  "cùn v",
  "r x",
  "hhhhh",
  "kkakak",
  "sao đú",
  "cặc con",
  "ngu kìa",
  "chat mạnh đê",
  "hăng ee",
  "ơ ơ ơ",
  "sủa cháy đê",
  "sủa mạnh eei",
    "thẩm du cái lồn má m lên :))",
    "con đĩ cãi cùn",
    "địt bà nội sư gia nhà m =))",
    "úi úi",
    "nhanh lên con chó lồn khai khắm=))",
    "sao con đĩ mẹ ày gà vậy",
    "địt lồn mẹ mày",
    "dập cặc thằng cha mày liền",
    "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
    "Con thú đú",
    "lòi lồn chiến sĩ rồi à",
    "sao không mạnh mẽ lên",
    "khép lép vậy",
    "sợ hãi rồi à",
    "Lẹ lên con điếm thúi",
    "con đĩ mồ coi ăn hôi",
    "thế nào rồi",
    "sợ anh mày chưa",
    "anh mày bá sàn mà",
    "sao m chối hoài",
    "chối là con má m die",
    "ngu thì ngu vừa thôi=))",
    "không t đâm chết thằng cha mày",
    "óc chó dữ",
    "lồn mẹ mày",
    "điếm thúi ơi=))",
    "đừng rớt nhây nhó:3",
    "thấy sao rùi:3",
    "Bede sủa tiếng nghe choiw",
    "Cặc Cặc Cặc",
    "Lồn Lồn Lồn",
    "=))",
    "Thấy anh nhây bá ko",
    "quá bá mà",
    "sao lại anh được",
    "khép đuôi xin tha đê",
    "Rủa đĩ má m die",
    "Ngồi nhây tới đêm trăng tròn nè=))",
    "Nhây sao lại anh",
    "Bóng sida",
    "bede dập cu ơi=))",
    "nhắm chửi lại anh không=))",
    "lẹ lên con đĩ",
    "điếm thúi ăn hôi ơi:))",
    "Lên xem còn tài cán gì không nào",
    "Sao mà xạo lồn",
    "Dân va 2023 à",
    "Chỉ có vậy thôi à",
    "mày làm được gì không😤",
    "hay chỉ biết phản kháng🤭=))",
    "tk cu bé phản kháng di😏?",
    "con đĩ cave luôn khảng phán đi",
    "bị chửi nên không phản kháng à",
    "con cave và tk cu bé hợp nhề😏",
    "con bede không phản kháng được à",
    "con bede sợ anh rồi:)",
    "chạy về mách mẹ à con bede",
    "chạy về trốn dô cái lồn mẹ mày đi?",
    "1 đứa bú lồn mẹ",
    "1 đứa bú cu cha",
    "bất hiếu cmnr:))",
    "mày làm gì để anh sợ đi:))",
    "mày có tý sát thương nào ko",
    "con đĩ mẹ mày ăn cứt cố đi",
    "mày sợ anh à con chó ăn cứt:))?",
    "anh win cmnr clm",
    "lũ cave cay cha cmnr",
    "cay anh  r à lũ đú",
    "sợ anh  à",
    "anh  win m mà:)))",
    "win nha clm bede🤣🤣",
    "sủa đi",
  "cố lên con",
  "sồn hăng lên em",
  "sao m yếu v ",
  "cố tí nữa",
  "sao kìa chậm à",
  "hăng hái lên tí chứ",
  "tới sáng đi em=))",
  "cố gắng tí con chó dốt=))",
  "k đc à",
  "con chó ngu cố đê",
  "sao m câm kìa",
  "gà j",
  "mày sợ anh à =))",
  "m gà mà",
  "mày ngu rõ mà",
  "đúng mà",
  "cãi à",
  "mày còn gì khác k",
  "học lỏm kìa",
  "cố tí em",
  "mếu à",
  "sao mếu kìa",
  "tao đã cho m mếu đâu",
  "va lẹ đi con dốt",
  "sao kìa",
  "từ bỏ r à",
  "mạnh mẽ tí đi con đĩ",
  "cố lên con chó ngu",
  "=)) cay tao à con đĩ",
  "sợ tao à",
  "sao sợ tao kìa",
  "cay lắm phải kh",
  "ớt rồi kìa em",
  "mày còn chối à",
  "làm tí đê",
  "mới đó đã mệt r kìa",
  "sao gà mà sồn v",
  "sồn như lúc đầu cho tao",
  "sao à",
    "thẩm du cái lồn má m lên :))",
    "con đĩ cãi cùn",
    "địt bà nội sư gia nhà m =))",
    "úi úi",
    "nhanh lên con chó lồn khai khắm=))",
    "sao con đĩ mẹ ày gà vậy",
    "địt lồn mẹ mày",
    "dập cặc thằng cha mày liền",
    "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
    "Con thú đú",
    "lòi lồn chiến sĩ rồi à",
    "sao không mạnh mẽ lên",
    "khép lép vậy",
    "sợ hãi rồi à",
    "Lẹ lên con điếm thúi",
    "con đĩ mồ coi ăn hôi",
    "thế nào rồi",
    "sợ anh mày chưa",
    "anh mày bá sàn mà",
    "sao m chối hoài",
    "chối là con má m die",
    "ngu thì ngu vừa thôi=))",
    "không t đâm chết thằng cha mày",
    "óc chó dữ",
    "lồn mẹ mày",
    "điếm thúi ơi=))",
    "đừng rớt nhây nhó:3",
    "thấy sao rùi:3",
    "Bede sủa tiếng nghe choiw",
    "Cặc Cặc Cặc",
    "Lồn Lồn Lồn",
    "=))",
    "Thấy anh nhây bá ko",
    "quá bá mà",
    "sao lại anh được",
    "khép đuôi xin tha đê",
    "Rủa đĩ má m die",
    "Ngồi nhây tới đêm trăng tròn nè=))",
    "Nhây sao lại anh",
    "Bóng sida",
    "bede dập cu ơi=))",
    "nhắm chửi lại anh không=))",
    "lẹ lên con đĩ",
    "điếm thúi ăn hôi ơi:))",
    "Lên xem còn tài cán gì không nào",
    "Sao mà xạo lồn",
    "Dân va 2023 à",
  "ai cho m nhai",
  "cay lắm r", 
  "từ bỏ đi em",
  "mày nghĩ mày làm t cay đc à",
  "có đâu",
  "tao đang hành m mà",
  "bịa à",
  "cay :)))))",
  "cố lên chó dốt",
  "hăng tiếp đi",
  "tới sáng k em",
  "k tới sáng à",
  "chán v",
  "m gà mà",
  "log acc thay phiên à",
  "coi tụi nó dồn ngu kìa",
  "sợ tao à con chó đần",
  "lại win à",
  "lại win r",
  "lũ cặc cay tao lắm🤣🤣",
  "cố lên đê",
  "sao mới 5p đã câm r",
  "yếu đến thế à",
  "sao kìa",
  "khóc kìa",
  "cầu cứu lẹ ei",
  "ai cứu đc m à :))",
  "tao bá mà",
  "sao m gà thế",
     "Lên xem còn tài cán gì không nào",
    "Sao mà xạo lồn",
    "Dân va 2023 à",
    "Chỉ có vậy thôi sao",
    "mày làm được gì không😤",
    "hay chỉ biết phản kháng🤭=))",
    "tk cu bé phản kháng di😏?",
    "con đĩ cave luôn khảng phán đi🥺?",
    "bị chửi nên không phản kháng à😀?",
    "con cave và tk cu bé hợp nhề😏👉",
    "2 con bede không phản kháng được à😋",
    "2 con bede sợ anh rồi:))🙃",
    "chạy về mách mẹ à 2 con bede😗?",
    "chạy về trốn dô cái lồn mẹ mày đi😍?",
    "1 đứa bú lồn mẹ😎?",
    "1 đứa bú cu cha😎?",
    "bất hiếu cmnr:))😜",
    "mày làm gì để anh sợ đi:))🤣?",
    "mày có tý sát thương nào ko😂?",
    "con đĩ mẹ mày ăn cứt cố đi🤣?",
    "mày sợ anh à con chó ăn cứt:))?",
    "anh win cmnr clm🤣",
    "lũ cave cay cha cmnr😑",
    "cay cha r à lũ đú😅",
    "sợ anh tao rồi à😗",
    "anh  win m mà:)))",
    "win nha clm bede🤣🤣",
     "con eii",
  "cố đeee",
  "sồn hăng lên em",
  "sao m yếu v",
  "cố tí nữa",
  "sao kìa chậm à",
  "hăng hái lên tí chứ",
  "tới sáng đi em eii",
  "cố gắng tí eii",
  "k đc à",
  "con eii cố de",
  "sao m câm kìa",
  "gà j",
  "tnh gà",
  "m gà mà",
  "dk à",
  "đúng mà",
  "cãi à",
  "mày còn gì khác k",
  "học lỏm kìa",
  "cố tí em",
  "mếu à",
  "sao mếu kìa",
  "tao đã cho m mếu đâu",
  "va lẹ eii",
  "sao kìa",
  "từ bỏ r à",
  "mạnh mẽ tí đi nà",
  "cố eii",
  ":)))",
  "sợ tao à",
  "sao sợ tao kìa",
  "cay lắm phải kh",
  "ớt rồi kìa em",
  "mày còn chối à",
  "làm tí đê",
  "mới đó đã mệt r kìa",
  "sao gà mà sồn v",
  "sồn như lúc đầu cho tao",
  "sao à",
  "ai cho m nhai",
  "cay lắm r", 
  "từ bỏ đi em",
  "mày nghĩ mày làm t cay đc à",
  "có đâu",
  "tao đang hành m mà",
  "bịa à",
  "cay :)))))",
  "cố eiii",
  "hăng tiếp đi",
  "tới sáng k em",
  "k tới sáng à",
  "chán v",
  "m gà mà",
  "log acc thay phiên à",
  "coi tụi nó dồn ngu kìa",
  "ae ơiii",
  "lại win à",
  "lại win r",
  "lũ cặc cay tao lắm🤣🤣",
  "cố lên đê",
  "sao mới 5p đã câm r",
  "yếu đến thế à",
  "sao kìa",
  "khóc kìa",
  "cầu cứu lẹ ei",
  "ai cứu đc m à :))",
  "tao bá mà",
  "sao m gà thế",
  "hăng lẹ cho tao",
  "con chó eiii🤣",
  "ổn k em",
  "kh ổn r à",
  "xin tha eii",
  "mẹ mày ngu à",
  "bú cặc cha m k em",
  "thg giả gái :))",
  "coi nó ngu kìa ae",
  "con chó này giả ngu à",
  "m ổn k",
  "mồ côi kìa",
  "sao v sợ r à",
  "cố gắng tí em",
  "cay cú lắm r",
  "đấy đấy bắt đầu",
  "chảy nước đái bò r à em",
  "sao kìa đừng run",
  "mày run à:))",
  "thg dái lở",
  "cay mẹ m lắm",
  "lgbt xuất trận ae eii",
  "thg cặc giết cha mắng mẹ",
  "sủa mạnh eii",
  "mày chết r à:))",
  "sao chết kìa",
  "bị t hành nên muốn chết à",
  "con lồn ngu=))",
  "sao kìa",
  "mạnh lên kìa",
  "yếu sinh lý à",
    "sủa đê",
  "cay à",
  "hăng đê",
  "gà kìa ae",
  "akakaa",
  "óc chó kìa",
  "🤣🤣🤣",
  "ổn không🤣🤣",
  "bất ổn à",
  "ơ kìaaa",
  "hăng hái đê",
  "chạy à 🤣🤣",
  "tởn à",
  "kkkk",
  "mày dốt à",
  "cặc ngu",
  "cháy đê",
  "chat hăng lên",
  "cố lên",
  "mồ côi cay",
  "cay à",
  "cn chó ngu",
  "óc cặc kìa",
  "đĩ đú:))",
  "đú kìa",
  "cùn v",
  "r x",
  "hhhhh",
  "kkakak",
  "sao đú",
  "cặc con",
  "ngu kìa",
  "chat mạnh đê",
  "hăng ee",
  "ơ ơ ơ",
  "sủa cháy đê",
  "sủa mạnh eei",
  "hăng lên đeeee",
  "sồn hăng lên em",
  "thấy m yếu ",
  "cố tí nha",
  "sao kìa chậm à",
  "hăng hái lên tí chứ",
  "tới sáng đi em eii",
  "cố gắng tí nữa sắp win r á",
  "kh đc à hay sao v",
  "con eii cố lên",
  "sao m câm kìa",
  "gà quá",
  "thằng đú",
  "m gà mà",
  "kh đc cãi",
  "m gà ",
  "mày con trò gì hay ho hơn kh",
  "mày còn gì khác k",
  "học lỏm kìa",
  "kh được méc mẹ nha",
  "khóc à",
  "sao mếu kìa",
  "tao đã cho m mếu đâu",
  "va lẹ eii",
  "sao kìa",
  "từ bỏ r à",
  "mạnh mẽ tí đi nà",
  "cố eii",
  "thứ đĩ",
  "sợ tao à",
  "sao sợ tao kìa",
  "cay lắm phải kh",
  "ớt anh lắm đk",
  "mày chối ăn cứt bò nhe ",
  "làm tí đê",
  "mới đó đã mệt r kìa",
  "sao gà mà sồn v",
  "sồn như lúc đầu cho tao",
  "sao à",
  "ai cho m nhai",
  "cay lắm r", 
  "từ bỏ đi em",
  "mày nghĩ mày làm t cay đc à",
  "có đâu",
  "tao đang hành m mà",
  "bịa à",
  "cay :)))))",
  "cố eiii",
  "hăng tiếp đi",
  "tới sáng k em",
  "k tới sáng à",
  "chán v",
  "m gà mà",
  "log acc thay phiên à",
  "coi tụi nó dồn ngu kìa",
  "ae ơiii",
  "lại win à",
  "lại win r",
  "lũ cặc cay tao lắm🤣🤣",
  "cố lên đê",
  "sao mới 5p đã câm r",
  "yếu đến thế à",
  "sao kìa",
  "khóc kìa",
  "cầu cứu lẹ ei",
  "ai cứu đc m à :))",
  "tao bá mà",
  "sao m gà thế",
  "hăng lẹ cho tao",
  "con chó eiii🤣",
  "ổn k em",
  "kh ổn r à",
  "xin tha eii",
  "mẹ mày ngu à",
  "bú cặc cha m k em",
  "thg giả gái :))",
  "coi nó ngu kìa ae",
  "con chó này giả ngu à",
  "m ổn k",
  "mồ côi kìa",
  "sao v sợ r à",
  "cố gắng tí em",
  "cay cú lắm r",
  "đấy đấy bắt đầu",
  "chảy nước đái bò r à em",
  "sao kìa đừng run",
  "mày run à:))",
  "thg dái hôi ê clm kk",
  "thg bede câm r kkkkk",
  "cay mẹ m lắm",
  "thứ bê đê xuất trận à kkkk",
  "thg cặc giết cha mắng mẹ",
  "sủa mạnh eii",
  "nào m chết vậy đĩ đú:))",
  "sao chết kìa",
  "bị t hành nên muốn chết à",
  "con lồn ngu=))",
  "sao kìa",
  "mạnh lên kìa",
  "yếu sinh lý à",
  "sủa đê",
  "cay à",
  "hăng đê",
  "gà kìa ae",
  "thấy thg này gà quá đi ae ơi",
  "óc chó kìa",
  "🤣🤣🤣",
  "ổn không🤣🤣",
  "bất ổn à",
  "ơ kìaaa",
  "hăng hái đê",
  "chạy à 🤣🤣",
  "thích réo cha à thằng ngu ",
  "mày đú mà ",
  "cặc hôi ",
  "óc vật đang sĩ gái rất hăng",
  "chat hăng lên",
  "cố lên",
  "mồ côi cay",
  "cay à",
  "cn chó ngu",
  "óc cặc kìa",
  "đĩ đú:))",
  "đú kìa",
  "cùn v",
  "roi xong",
  "hhhhh",
  "kkakak",
  "sao đú",
  "cặc con",
  "ngu kìa",
  "chat mạnh đê",
  "hăng ee",
  "ơ ơ ơ",
  "sủa cháy đê",
  "sủa mạnh eei",
    "ổn kh đó thg ngu",
    "m đg bất lực đúng kh nè",
    "súc vật tưởng mình ngầu",
    "đừng ra vẻ nữa đĩ đú ơi",
    "cha chửi là m chỉ bt câm clm kk",
    "Sủa đi ơ ai cho m câm m sợ cha rõ mà p",
  "Ai cho m run hả con đĩ m sợ cha rõ",
  "M có sức ảnh hưởng hả ccho dốt", 
  "Ngóng tai mà nghe bố qv mày chửi nè",
  "Cay cha m rõ mà xạo lồn afaaa culi đi đú ửa kìa ơ ơ",
  "Đỉ mẹ m ai cho m câm vậy hả con chó ngu  thôi nè k cay cha m cho bú cặc nha con đúuu",
  "CON CHÓ NHAI LẠI NGÔN KÌA😜",
  "gia phúc trùm sàn nhây đó lũ đú ",
  "Đú ngu như chó đú đú cái lồn mẹ m hả dốt cay kìa sao m ngu m cứ đú hoài v hả con chó óc cặc ê sao m yếu đuối thể hả hăng hái lên đê ai cho m đuối v con chó ngu",
  "Ớt m nè đú ê sao đó không được cay cha nha",
  "Culi đi đú ửa kìa ơ ơ",
  "Sủa đi ơ ai cho m câm m sợ cha rõ",
  "Địt cái lồn mẹ mày chết chưa hả thằng lồn",
  "thằng ngu lgbt da đen sủa lẹ ai cko mày câm",
    "ccho svbbắc kì tao cko mày câm đaau",
  "hăng lẹ cho tao",
  "con chó eiii🤣",
  "ổn k em",
  "kh ổn r à",
  "mày óc à con chó bẻm=))",
  "mẹ mày ngu à",
  "bú cặc cha m k em",
  "thg giả gái :))",
  "coi nó ngu kìa ae",
  "con chó này giả ngu à",
  "m ổn k",
  "mồ côi kìa",
  "sao v sợ r à",
  "cố gắng tí em",
  "cay cú lắm r",
  "đấy đấy bắt đầu",
  "chảy nước đái bò r à em",
  "sao kìa đừng run",
  "mày run à:))",
  "thg dái lở",
  "cay mẹ m lắm",
  "lgbt xuất trận à con đĩ",
  "thg cặc giết cha mắng mẹ",
  "sủa mạnh eii",
  "mày chết r à:))",
  "sao chết kìa",
  "bị t hành nên muốn chết à",
  "con lồn ngu=))",
  "sao kìa",
  "mạnh lên kìa",
  "yếu sinh lý à",
    "sủa đê",
  "cay à",
  "hăng đê",
  "gà kìa ae",
  "akakaa",
  "óc chó kìa",
    "Thằng ngu sủa anh nghe đi",
    "Sồn lên đi con chó óc dái",
    "mày tật à con đĩ",
    "clm hăng lên cha xem đi",
    "nào bằng cha vậy súc vật",
  "Đĩ Mẹ Mày Hăng đi con chó",
    "Chó Cay Nên Cắn Anh Kìa",
    "Cái Lồn Mày Yếu Vậy",
    "Nhanh Lên Tao Xem Nào",
    "Hà Bá À thằng óc",
    "lồn mẹ mày bị cha đụ nát này ",
    "sồn lên đi con súc vật ",
    "Đang Cay Cha à",
    "Cố Lên Sắp Ngầu rồi",
  "Lồn Mẹ mày Óc Vc",
    "Thằng Gà",
    "Đĩ mẹ mày phèn",
    "mày óc lồn rõ 🙄",
    "sủa đi ớ",
    "yếu vậy",
    "Con Chó Hăng Lên Cha Xem",
    "Đĩ Mẹ Mày Béo",
    "ZedNos đến giết mày này con chó óc dái",
    "cái lồn mày hăng lên đi",
    "Óc Dái Cay Cha Kiểu",
    "ZN Bá Mà Đúng Không?",
    "Con Mẹ Mày Óc Êy",
    "ZN Là Cha Mày Mà Nghịch Tử",
    "Cố Phản Kháng Cha Đi Ớ",
    "Mày Óc Đúng Không",
    "Đừng Sồn Nữa",
    "Cha Cho Xương Nè",
    "Cl Mày Cắn Người Thế",
    "Yếu Kém À",
    "nhanh lên đi súc vật ",
    "ZN Bá Mà Con Chó",
    "Cha Bá Cmmnr ",
    "Yếu Sinh Lý À",
    "Sao Lâu Thế",
    "Đang Cố Biện Minh À",
    "Mày Óc Đến Cỡ Nào Vậy",
    "Sao Chậm =))",
    "nhanh lên tí đi nào",
    "ZN Bá Sàn Mà Cu Li",
    "Óc Chó Xin Cha Tha Thứ",
    "Đừng Sồn Nữa Clm",
    "Sao Phế Vậy",
    "Nhanh Lên Tao Xem Nào",
       "Con Đĩ Mẹ Mày Béo À",
    "Chỉ Thế Thôi Á",
    "Phèn Vậy",
    "Va cha là mày Ngu",
    "Óc Dái Không Dám Care à",
    "Thua Con Mẹ Mày Hấp Hối",
    "ớt cha cmmnr",
    "làm cha cay đi ớ",
    "Tao Là Nghịch Thiên Mày Là Nghịch Tử Á",
    "Làm Cha Cay Đi Ớ",
    "Cu Li Cay Cha Kiểu", 
   "ổn không em",
     "run anh à",
     "con mẹ mày cay à",
     "hăng lên đi nào",
     "chó óc sủa đi em",
     "anh cho mày sủa à",
     "nào hết xàm lồn vậy em",
    "nhiều mày sồn mắt cười quá em",
     "speed khi gõ được không ?",
     "sao slow vậy em",
   "fast tí được không chó dốt",
     "Spicy cha đỏ đái",
     "đang ignore đúng không thằng dốt",
    "sao slow thế speed đi nào em",
     "em chicken mà",
     "đang không hiểu gì à",
     "sao mày dốt thế",
     "english cơ bản đó thằng culi",
     "con mẹ mày óc bò à",
     "óc chó não tật đúng không",
     "ngu cứ tỏ ra  understand à",
     "dog dốt đang ngơ cha",
     "sao không seen?",
     "bị cha chửi đến ngu à 🙄",
     "cái lồn mày gà vậy em ",
     "Ghệ mày đang chat sex với tao nè 🤣",
     "thằng ysl tinh trùng ít nữa",
     "clm sủa à",
     "dốt cmmnr",
     "run cha đi",
     "get out được không em???",
     "óc chó à cu",
     "sao nhìn mày gõ toàn câu xàm lồn vậy",
     "phím tắt nhan hơn anh không?",
     "sao em gà vậy??",
     "nhanh lên đi nào ớ",
     "cố gắng làm cha cay đi em",
     "thằng nhóc bú lồn mẹ 🙄",
     "lên mạng xàm lồn với cha kìa",
     "ớt cha đỏ con cặc",
     "cần anh cho chó gãi dùm không",
    "mẹ mày đang phản kháng cha mà",
  "con mẹ mày đang quỳ lại tao kìa 😏",
    "tha cho thằng bất hiếu như mày",
    "ZN tao bá mà 💮🎭",
    "Hăng Hái Lên Nào Sao Chậm Vậy",
    "Ai cứu được mày vậy",
    "tag vào tao xem đi 🙄🙄",
    "con đĩ mẹ mày đang hấp hối kìa",
    "mày gà đúng không",
    "speed đi nào",
    "chậm vậy nhóc ác",
    "hăng với ai vậy con dốt",
    "cay cha đỏ con cặc kìa",
    "cái lồn mày cay cha à",
    "sao khóc rồi",
    "clm đừng khóc nữa ",
    "vang xin anh đi rồi anh tha nhé",
    "ngu ngục hả emm",
    "con mẹ mày nào lớn á 🤓",
    "óc chó gõ kiểu:",
    "ai cứu được mày vậy alo",
    "con chó lên cha biểu đi nào",
    "cái lồn mày câm à",
    "nhanh lên được không",
    "yếu vậy chưa ăn cơm à",
    "cái lồn mày speed đi em",
    "chậm vậy",
    "làm cha cay đi cu dái",
    "thằng cha mày vang xin anh tha kìa",
    "đĩ lgbt cay cha đỏ dái",
    "con mẹ mày gay mà óc vậy",
    "nhanh lên tí được không",
    "óc chó ngu kìa",
    "úi úi",
    "cay cha đỏ con cặc rõ",
    "cái lồn mày nhại ngôn à",
    "speed đi em ey",
    "con đĩ mẹ mày hấp hối kìa",
    "nhây 24h không em",
    "con mẹ mày đú dữ",
    "óc chó à",
    "cái lồn mày mếu à",
    "kakakaka cay ",
    "cười đến nội thương clm",
    "chó ơi", 
    " sủa đi",
  "cố lên con",
  "sồn hăng lên em",
  "sao m yếu v ",
  "cố tí nữa",
  "sao kìa chậm à",
  "hăng hái lên tí chứ",
  "tới sáng đi em=))",
    "Thằng ngu sủa anh nghe đi",
    "Sồn lên đi con chó óc dái",
    "mày tật à con đĩ",
    "clm hăng lên cha xem đi",
    "nào bằng cha vậy súc vật",
  "Đĩ Mẹ Mày Hăng đi con chó",
  "cố gắng tí con chó dốt=))",
  "k đc à",
  "con chó ngu cố đê",
  "sao m câm kìa",
  "gà j",
  "mày sợ anh à =))",
  "m gà mà",
  "mày ngu rõ mà",
  "đúng mà",
  "cãi à",
  "mày còn gì khác k",
  "học lỏm kìa",
  "cố tí em",
  "mếu à",
  "sao mếu kìa",
  "tao đã cho m mếu đâu",
  "va lẹ đi con dốt",
  "sao kìa",
  "từ bỏ r à",
  "mạnh mẽ tí đi con đĩ",
  "cố lên con chó ngu",
  "=)) cay tao à con đĩ",
  "sợ tao à",
  "sao sợ tao kìa",
  "cay lắm phải kh",
  "ớt rồi kìa em",
  "mày còn chối à",
  "làm tí đê",
  "mới đó đã mệt r kìa",
  "sao gà mà sồn v",
  "sồn như lúc đầu cho tao",
  "sao à",
  "ai cho m nhai",
      "run anh à",
     "con mẹ mày cay à",
     "hăng lên đi nào",
     "chó óc sủa đi em",
     "anh cho mày sủa à",
     "nào hết xàm lồn vậy em",
    "nhiều mày sồn mắt cười quá em",
     "speed khi gõ được không ?",
     "sao slow vậy em",
   "fast tí được không chó dốt",
     "Spicy cha đỏ đái",
  "cay lắm r", 
  "từ bỏ đi em",
  "mày nghĩ mày làm t cay đc à",
  "có đâu",
  "tao đang hành m mà",
  "bịa à",
  "cay :)))))",
  "cố lên chó dốt",
  "hăng tiếp đi",
  "tới sáng k em",
  "k tới sáng à",
  "chán v",
  "m gà mà",
  "log acc thay phiên à",
  "coi tụi nó dồn ngu kìa",
  "sợ tao à con chó đần",
  "lại win à",
  "lại win r",
  "lũ cặc cay tao lắm🤣🤣",
  "cố lên đê",
  "sao mới 5p đã câm r",
  "yếu đến thế à",
  "sao kìa",
  "khóc kìa",
  "cầu cứu lẹ ei",
  "ai cứu đc m à :))",
  "tao bá mà",
  "sao m gà thế",
  "hăng lẹ cho tao",
     "Thằng Gà",
    "Đĩ mẹ mày phèn",
    "mày óc lồn rõ 🙄",
    "sủa đi ớ",
    "yếu vậy",
    "Con Chó Hăng Lên Cha Xem",
    "Đĩ Mẹ Mày Béo",
    "ZedNos đến giết mày này con chó óc dái",
    "cái lồn mày hăng lên đi",
    "Óc Dái Cay Cha Kiểu",
    "ZN Bá Mà Đúng Không?",
    "Con Mẹ Mày Óc Êy",
    "ZN Là Cha Mày Mà Nghịch Tử",
    "Cố Phản Kháng Cha Đi Ớ",
    "Mày Óc Đúng Không",
  "con chó eiii🤣",
  "ổn k em",
  "kh ổn r à",
  "mày óc à con chó bẻm=))",
  "mẹ mày ngu à",
  "bú cặc cha m k em",
  "thg giả gái :))",
  "coi nó ngu kìa ae",
  "con chó này giả ngu à",
  "m ổn k",
  "mồ côi kìa",
  "sao v sợ r à",
  "cố gắng tí em",
  "cay cú lắm r",
  "đấy đấy bắt đầu",
  "chảy nước đái bò r à em",
  "sao kìa đừng run",
  "mày run à:))",
  "thg dái lở",
  "cay mẹ m lắm",
  "lgbt xuất trận à con đĩ",
  "thg cặc giết cha mắng mẹ",
  "sủa mạnh eii",
  "mày chết r à:))",
  "sao chết kìa",
  "bị t hành nên muốn chết à",
  "con lồn ngu=))",
  "sao kìa",
  "mạnh lên kìa",
  "yếu sinh lý à",
  "sủa đê",
  "cay à",
  "hăng đê",
  "gà kìa ae",
  "akakaa",
  "óc chó kìa",
  "🤣🤣🤣",
  "ổn không🤣🤣",
  "bất ổn à",
  "ơ kìaaa",
  "hăng hái đê",
    "mày gà đúng không",
    "speed đi nào",
    "chậm vậy nhóc ác",
    "hăng với ai vậy con dốt",
    "cay cha đỏ con cặc kìa",
    "cái lồn mày cay cha à",
    "sao khóc rồi",
    "clm đừng khóc nữa ",
    "vang xin anh đi rồi anh tha nhé",
    "ngu ngục hả emm",
    "con mẹ mày nào lớn á 🤓",
    "óc chó gõ kiểu:",
  "chạy à 🤣🤣",
  "tởn à",
  "kkkk cay cha cmmnr ",
  "mày dốt à",
  "cặc ngu",
  "cháy đê",
  "chat hăng lên",
  "cố lên",
  "mồ côi cay",
  "cay à",
  "cn chó ngu",
  "óc cặc kìa",
  "đĩ đú:))",
  "đú kìa",
  "cùn v",
  "rồi xong nhỏ khóc luôn",
  "haiz chán thật",
  "nhìn đú mất mệt",
  "sao đú",
  "cặc con",
  "ngu kìa",
  "chat mạnh đê",
  "hăng ee",
  "ơ ơ ơ",
  "sủa cháy đê",
  "sủa mạnh eei",
  "mày óc à con",
  "tao cho m chạy à",
  "con đĩ ngu sủa?",
  "mày chạy à con đĩ lồn",
  "sao chậm vậy",
  "nhanh lên cha xem nào",
  "cay cha à",
  "cố kháng cự cha à",
  "Nguyễn Gia Phúc Anh Bá Cmnr",
  "Cố Lên Sắp Ngầu = Chó Rồi",
  " Nghịch Tử Đang Cố Loạn Luân Mẹ Ruột Trước Mặt Cha ",
  "Thằng Nghịch Tử Đang Cố Phản Kháng Anh",
  "Có Lớn Đéo Có Khôn Phải Nhờ Cha Dậy Chữ Hiếu Và Chữ Trọng",
  "Thằng Lồn",
  "hăng đi con chó ngu ăn cứt 💩",
  "Địt Mẹ Sao Lại Vang Xin Anh Tha Vậy?",
  "Thằng Núi Nhìn Trong Phèn Làm Sao",
  "nào ngầu bằng anh?",
  "Cố Lên Đi Nào",
  "Chậm Thế",
  "Nhanh Lên Đi",
  "Nhìn Mày Phèn Vc",
  "sao lại cay anh hả",
  "mãi chưa bằng anh nhìn tội nghiệp vc",
  "Nghịch Tử Đang Cố Phản Kháng Cha",
  "địt mẹ thằng bất hiếu",
  "giết cha đụ mẹ",
  "cầm con cặc đụ lồn chó",
  "cặc nhỏ tới nổi chó tao khinh",
  "Nào Hết Ngu Vậy Nói Cha Nghe",
  "ơ thằng cặc đi đâu đây",
  "nhìn mày như mấy thằng đụ gái sì ke vậy",
  "bị lây hiv dẫn đến ngu",
  "nhìn mày ảo mà tao mệt dùm",
  "lên mxh cứ ảo war giúp gì cho mày được không",
  "nhìn mày như mấy đứa óc lồn lên mạng ảo mxh",
  "nhìn ngu chết đĩ mẹ tưởng mình hay à",
  "gõ nhanh lên tao xem nào",
   "nhanh lên tao xem", 
  "sao mày gõ chậm thế",
  "gõ ngu thế kia",
  "nhìn mày trong phèn vãi",
  "mãi chưa lớn",
  "mày bắc kì à sao ngu vậy",
  "con chó sủa cha nghe🐶",
  "sủa lớn lên cho cha nghe đi",
  "nhanh lên cha xem",
  "Ngu Như 🐮",
  "nhìn mày sôn như 1 con chó",
  "Nhìn mày tật đến đáng thương",
  "Sao mày hay đú vậy", 
  "ảo mxh là thói quen của con chó như mày à", 
  "nếu một mai gặp anh thì hãy out nhé",
  "xạo lồn trước mặt anh",
  "nhìn mày sủa tiếng chó nghe nhức đầu vc", 
  "sao vậy", 
  "thằng đĩ", 
    "sôn lên cha xem",
    "đụ mẹ mày đến chết",
    "thằng nghịch tử loạn luận mẹ ruột",
    "địt mẹ mày",
    "Mày Sống Như Lồn",
    "đéo để đức cho con cháu",
  "lên mạng cứ xàm lồn",
  "tưởng vậy là hay lắm à thằng ngu", 
  "ngu mà hay xạo lồn",
  "mày xàm lồn gì vậy",
    "địt mẹ thằng ngu",
    "cạn ngôn đến ngu",
  "sao lại yếu thế kia",
  "nhanh lên tao xem nào",
  "mày ngu mà",
   "thằng não cặc đang cố biện minh", 
  "Thằng lồn ơi",
    "sắp ngầu rồi cố lên",
    "thằng ngu sắp ngầu rồi",
    "mày óc mà thằng lồn",
      "nhanh lên tao xem nào",
      "mày chậm thế",
      "nhanh lên đi con chó",
      "thằng đĩ óc cặc cay cha",
      "sao mày nhảm vậy",
      "ớt cha à 🤣",
      "mày cay cmmnr",
      "óc chó ơi 🐶",
      "sủa cha nghe 🐶",
      "mẹ mày đang hấp hối kìa",
      "cha mày đang truy tìm mày kìa",
      "kiếm để chém thằng nghịch tử như mày",
      "loạn luân mẹ ruột à thằng nghịch tử",
      "địt mẹ đời mày như lồn á",
      "gặp anh là do mày ngu rồi 🤣👈",
      "sao gõ chậm",
      "nhanh lên tao xem",
      "chậm vậy thằng óc cặc",
      "nhanh lên cha xem",
      "muốn run lắm à",
      "sao tao thấy mày cứ sợ tao à",
      "nhìn cay đỏ dái",
      "không trêu nghịch tử nè",
      "nghịch tử sắp về méc mẹ á 🤣👈",
      "nghịch tử đang run sợ anh à",
      "sao khóc nói anh nghe",
      "chơi không có méc mẹ nè 🤣",
      "sợ thì out đi 🐶",
     "cố gắng làm cha cay đi em",
     "thằng nhóc bú lồn mẹ 🙄",
     "lên mạng xàm lồn với cha kìa",
     "ớt cha đỏ con cặc",
     "cần anh cho chó gãi dùm không",
    "mẹ mày đang phản kháng cha mà",
  "con mẹ mày đang quỳ lại tao kìa 😏",
    "tha cho thằng bất hiếu như mày",
    "ZN tao bá mà 💮🎭",
    "Hăng Hái Lên Nào Sao Chậm Vậy",
    "Ai cứu được mày vậy",
    "tag vào tao xem đi 🙄🙄",
    "con đĩ mẹ mày đang hấp hối kìa",
    "mày gà đúng không",
    "speed đi nào",
    "chậm vậy nhóc ác",
      "mày bại gõ mà thằng ngu",
      "mãi bại thôi thằng ngu à",
      "ửa với anh đừng có méc mẹ nhá 🤣🤣",
      "sợ mày đang khóc lắm 🤣",
      "gặp cha là mày xui lắm con",
      "cố thể hiện để hơn cha nè",
      "cố lên đi sắp giống con chó rồi 😏🤣",
      "cố chạy đi thằng nhóc",
      "sợ cha cmnr",
      "mày đang run sợ anh à 🤣",
      "thằng nghịch tử đừng cay anh nha 😝😜",
      "ớt cha à cay cmnr 😜🤣",
      "gõ nhanh lên thằng ngu",
      "thua tao là thế???",
      "nguyễn gia phúc anh làm mày sợ à",
      "nghịch tử đang cố cay cha 🤣",
      "nhanh lên xem nào ớ",
    "gõ nhanh lên xem nào",
    "chậm vậy mày gà à",
    "sao gõ chậm thế",
    "tao gõ bá cmnr",
    "mày óc cặc",
    "mày ngu lồn ớ 🐶",
    "con chó nghe lời cha quá",
    "mày gà mà ớ",
    "sao mày mãi gà thế",
    "nhanh lên tí được không?",
    "tao nhìn mày gõ tao buồn ngủ vc",
    "mày mãi gà mà thằng ngu",
    "mày gà vậy",
    "gõ đi thằng óc", 
    "nhanh lên đi",
    "lên trời cao không em",
    "đi chết kìa thằng dái",
    "con mẹ mày ngu à",
    "gà + óc = mày",
    "công nhận mày ngu vc",
    "cố sồn như chó à",
    "sao bằng anh được vậy hả cu",
    " mày mãi gà ớ",
    "nhìn mày tật đến đáng thương",
    "mày óc dái mà",
    "vc đụ mẹ ruột à",
    "thằng nghịch tử ổn không???",
    "nghịch thiên là cha mà ",
    "ngày tử của mày á con chó", 
    "đang cay anh đúnh không",
  "rất ớt cha cmmnr",
  "cay đến đỏ cặc à",
  "cha cho mày sồn à",
  "à quên mày sv sao nghe hiểu",
  "thằng cứt dái bò",
    "óc lợn ngu như bò ",
     "cặc nhỏ xíu",
     "chị mày bị tao đụ đến vang xin nè ",
     "mày thấy tao tài không ớ ",
   "bị tao đụ đến khóc rồi ",
     "vì xin tha cho mày á ",
     "thằng ngu à ",
    "mếu cha cmmnr",
    "ZN Bá Vc",
    "ZN Anh Chuyên Trị Mấy Thằng Ngu Như Mày",
    "Gà Mà Hay Sủa à 🤣🤣",
    "tật nói chuyện kiểu",
  "🤣🤣🤣",
  "ổn không🤣🤣",
  "bất ổn à",
  "ơ kìaaa",
  "hăng hái đê",
  "chạy à 🤣🤣",
  "tởn à",
  "kkkk",
  "mày dốt à",
  "cặc ngu",
  "cháy đê",
  "chat hăng lên",
  "cố lên",
  "mồ côi cay",
  "cay à",
  "cn chó ngu",
  "óc cặc kìa",
  "đĩ đú:))",
  "đú kìa",
  "cùn v",
  "r x",
  "hhhhh",
  "kkakak",
  "sao đú",
  "cặc con",
  "ngu kìa",
  "chat mạnh đê",
  "hăng ee",
  "ơ ơ ơ",
  "sủa cháy đê",
  "sủa mạnh eei",
  "mày óc à con",
  "tao cho m chạy à",
  "con đĩ ngu sủa?",
  "mày chạy à con đĩ lồn",
    "Thằng ngu sủa anh nghe đi",
    "Sồn lên đi con chó óc dái",
    "mày tật à con đĩ",
    "clm hăng lên cha xem đi",
    "nào bằng cha vậy súc vật",
  "Đĩ Mẹ Mày Hăng đi con chó",
    "Chó Cay Nên Cắn Anh Kìa",
    "Cái Lồn Mày Yếu Vậy",
    "Nhanh Lên Tao Xem Nào",
    "Hà Bá À thằng óc",
    "lồn mẹ mày bị cha đụ nát này ",
    "sồn lên đi con súc vật ",
    "Đang Cay Cha à",
    "Cố Lên Sắp Ngầu rồi",
  "Lồn Mẹ mày Óc Vc",
    "Thằng Gà",
    "Đĩ mẹ mày phèn",
    "mày óc lồn rõ 🙄",
    "sủa đi ớ",
    "yếu vậy",
    "Con Chó Hăng Lên Cha Xem",
    "Đĩ Mẹ Mày Béo",
    "ZedNos đến giết mày này con chó óc dái",
    "cái lồn mày hăng lên đi",
    "Óc Dái Cay Cha Kiểu",
    "ZN Bá Mà Đúng Không?",
    "Con Mẹ Mày Óc Êy",
    "ZN Là Cha Mày Mà Nghịch Tử",
    "Cố Phản Kháng Cha Đi Ớ",
    "Mày Óc Đúng Không",
    "Đừng Sồn Nữa",
    "Cha Cho Xương Nè",
    "Cl Mày Cắn Người Thế",
    "Yếu Kém À",
    "nhanh lên đi súc vật ",
    "ZN Bá Mà Con Chó",
    "Cha Bá Cmmnr ",
    "Yếu Sinh Lý À",
    "Sao Lâu Thế",
    "Đang Cố Biện Minh À",
    "Mày Óc Đến Cỡ Nào Vậy",
    "Sao Chậm =))",
    "nhanh lên tí đi nào",
    "ZN Bá Sàn Mà Cu Li",
    "Óc Chó Xin Cha Tha Thứ",
    "Đừng Sồn Nữa Clm",
    "Sao Phế Vậy",
    "Nhanh Lên Tao Xem Nào",
       "Con Đĩ Mẹ Mày Béo À",
    "Chỉ Thế Thôi Á",
    "Phèn Vậy",
    "Va cha là mày Ngu",
    "Óc Dái Không Dám Care à",
    "Thua Con Mẹ Mày Hấp Hối",
    "ớt cha cmmnr",
    "làm cha cay đi ớ",
    "Tao Là Nghịch Thiên Mày Là Nghịch Tử Á",
    "Làm Cha Cay Đi Ớ",
    "Cu Li Cay Cha Kiểu", 
   "ổn không em",
     "run anh à",
     "con mẹ mày cay à",
     "hăng lên đi nào",
     "chó óc sủa đi em",
     "anh cho mày sủa à",
     "nào hết xàm lồn vậy em",
    "nhiều mày sồn mắt cười quá em",
     "speed khi gõ được không ?",
     "sao slow vậy em",
   "fast tí được không chó dốt",
     "Spicy cha đỏ đái",
     "đang ignore đúng không thằng dốt",
    "sao slow thế speed đi nào em",
     "em chicken mà",
     "đang không hiểu gì à",
     "sao mày dốt thế",
     "english cơ bản đó thằng culi",
     "con mẹ mày óc bò à",
     "óc chó não tật đúng không",
     "ngu cứ tỏ ra  understand à",
     "dog dốt đang ngơ cha",
     "sao không seen?",
     "bị cha chửi đến ngu à 🙄",
     "cái lồn mày gà vậy em ",
     "Ghệ mày đang chat sex với tao nè 🤣",
     "thằng ysl tinh trùng ít nữa",
     "clm sủa à",
     "dốt cmmnr",
     "run cha đi",
     "get out được không em???",
     "óc chó à cu",
     "sao nhìn mày gõ toàn câu xàm lồn vậy",
     "phím tắt nhan hơn anh không?",
     "sao em gà vậy??",
     "nhanh lên đi nào ớ",
     "cố gắng làm cha cay đi em",
     "thằng nhóc bú lồn mẹ 🙄",
     "lên mạng xàm lồn với cha kìa",
     "ớt cha đỏ con cặc",
     "cần anh cho chó gãi dùm không",
    "mẹ mày đang phản kháng cha mà",
  "con mẹ mày đang quỳ lại tao kìa 😏",
    "tha cho thằng bất hiếu như mày",
    "ZN tao bá mà 💮🎭",
    "Hăng Hái Lên Nào Sao Chậm Vậy",
    "Ai cứu được mày vậy",
    "tag vào tao xem đi 🙄🙄",
    "con đĩ mẹ mày đang hấp hối kìa",
    "mày gà đúng không",
    "speed đi nào",
    "chậm vậy nhóc ác",
    "hăng với ai vậy con dốt",
    "cay cha đỏ con cặc kìa",
    "cái lồn mày cay cha à",
    "sao khóc rồi",
    "clm đừng khóc nữa ",
    "vang xin anh đi rồi anh tha nhé",
    "ngu ngục hả emm",
    "con mẹ mày nào lớn á 🤓",
    "óc chó gõ kiểu:",
    "ai cứu được mày vậy alo",
    "con chó lên cha biểu đi nào",
    "cái lồn mày câm à",
    "nhanh lên được không",
    "yếu vậy chưa ăn cơm à",
    "cái lồn mày speed đi em",
    "chậm vậy",
    "làm cha cay đi cu dái",
    "thằng cha mày vang xin anh tha kìa",
    "đĩ lgbt cay cha đỏ dái",
    "con mẹ mày gay mà óc vậy",
    "nhanh lên tí được không",
    "óc chó ngu kìa",
    "úi úi",
    "cay cha đỏ con cặc rõ",
    "cái lồn mày nhại ngôn à",
    "speed đi em ey",
    "con đĩ mẹ mày hấp hối kìa",
    "nhây 24h không em",
    "con mẹ mày đú dữ",
    "óc chó à",
    "cái lồn mày mếu à",
    "kakakaka cay ",
    "cười đến nội thương clm",
    "chó ơi", 
    " sủa đi",
  "cố lên con",
  "sồn hăng lên em",
  "sao m yếu v ",
  "cố tí nữa",
  "sao kìa chậm à",
  "hăng hái lên tí chứ",
  "tới sáng đi em=))",
    "Thằng ngu sủa anh nghe đi",
    "Sồn lên đi con chó óc dái",
    "mày tật à con đĩ",
    "clm hăng lên cha xem đi",
    "nào bằng cha vậy súc vật",
  "Đĩ Mẹ Mày Hăng đi con chó",
  "cố gắng tí con chó dốt=))",
  "k đc à",
  "con chó ngu cố đê",
  "sao m câm kìa",
  "gà j",
  "mày sợ anh à =))",
  "m gà mà",
  "mày ngu rõ mà",
  "đúng mà",
  "cãi à",
  "mày còn gì khác k",
  "học lỏm kìa",
  "cố tí em",
  "mếu à",
  "sao mếu kìa",
  "tao đã cho m mếu đâu",
  "va lẹ đi con dốt",
  "sao kìa",
  "từ bỏ r à",
  "mạnh mẽ tí đi con đĩ",
  "cố lên con chó ngu",
  "=)) cay tao à con đĩ",
  "sợ tao à",
  "sao sợ tao kìa",
  "cay lắm phải kh",
  "ớt rồi kìa em",
  "mày còn chối à",
  "làm tí đê",
  "mới đó đã mệt r kìa",
  "sao gà mà sồn v",
  "sồn như lúc đầu cho tao",
  "sao à",
  "ai cho m nhai",
      "run anh à",
     "con mẹ mày cay à",
     "hăng lên đi nào",
     "chó óc sủa đi em",
     "anh cho mày sủa à",
     "nào hết xàm lồn vậy em",
    "nhiều mày sồn mắt cười quá em",
     "speed khi gõ được không ?",
     "sao slow vậy em",
   "fast tí được không chó dốt",
     "Spicy cha đỏ đái",
  "cay lắm r", 
  "từ bỏ đi em",
  "mày nghĩ mày làm t cay đc à",
  "có đâu",
  "tao đang hành m mà",
  "bịa à",
  "cay :)))))",
  "cố lên chó dốt",
  "hăng tiếp đi",
  "tới sáng k em",
  "k tới sáng à",
  "chán v",
  "m gà mà",
  "log acc thay phiên à",
  "coi tụi nó dồn ngu kìa",
  "sợ tao à con chó đần",
  "lại win à",
  "lại win r",
  "lũ cặc cay tao lắm🤣🤣",
  "cố lên đê",
  "sao mới 5p đã câm r",
  "yếu đến thế à",
  "sao kìa",
  "khóc kìa",
  "cầu cứu lẹ ei",
  "ai cứu đc m à :))",
  "tao bá mà",
  "sao m gà thế",
  "hăng lẹ cho tao",
     "Thằng Gà",
    "Đĩ mẹ mày phèn",
    "mày óc lồn rõ 🙄",
    "sủa đi ớ",
    "yếu vậy",
    "Con Chó Hăng Lên Cha Xem",
    "Đĩ Mẹ Mày Béo",
    "ZedNos đến giết mày này con chó óc dái",
    "cái lồn mày hăng lên đi",
    "Óc Dái Cay Cha Kiểu",
    "ZN Bá Mà Đúng Không?",
    "Con Mẹ Mày Óc Êy",
    "ZN Là Cha Mày Mà Nghịch Tử",
    "Cố Phản Kháng Cha Đi Ớ",
    "Mày Óc Đúng Không",
  "con chó eiii🤣",
  "ổn k em",
  "kh ổn r à",
  "mày óc à con chó bẻm=))",
  "mẹ mày ngu à",
  "bú cặc cha m k em",
  "thg giả gái :))",
  "coi nó ngu kìa ae",
  "con chó này giả ngu à",
  "m ổn k",
  "mồ côi kìa",
  "sao v sợ r à",
  "cố gắng tí em",
  "cay cú lắm r",
  "đấy đấy bắt đầu",
  "chảy nước đái bò r à em",
  "sao kìa đừng run",
  "mày run à:))",
  "thg dái lở",
  "cay mẹ m lắm",
  "lgbt xuất trận à con đĩ",
  "thg cặc giết cha mắng mẹ",
  "sủa mạnh eii",
  "mày chết r à:))",
  "sao chết kìa",
  "bị t hành nên muốn chết à",
  "con lồn ngu=))",
  "sao kìa",
  "mạnh lên kìa",
  "yếu sinh lý à",
  "sủa đê",
  "cay à",
  "hăng đê",
  "gà kìa ae",
  "akakaa",
  "óc chó kìa",
  "🤣🤣🤣",
  "ổn không🤣🤣",
  "bất ổn à",
  "ơ kìaaa",
  "hăng hái đê",
    "mày gà đúng không",
    "speed đi nào",
    "chậm vậy nhóc ác",
    "hăng với ai vậy con dốt",
    "cay cha đỏ con cặc kìa",
    "cái lồn mày cay cha à",
    "sao khóc rồi",
    "clm đừng khóc nữa ",
    "vang xin anh đi rồi anh tha nhé",
    "ngu ngục hả emm",
    "con mẹ mày nào lớn á 🤓",
    "óc chó gõ kiểu:",
  "chạy à 🤣🤣",
  "tởn à",
  "kkkk cay cha cmmnr ",
  "mày dốt à",
  "cặc ngu",
  "cháy đê",
  "chat hăng lên",
  "cố lên",
  "mồ côi cay",
  "cay à",
  "cn chó ngu",
  "óc cặc kìa",
  "đĩ đú:))",
  "đú kìa",
  "cùn v",
  "rồi xong nhỏ khóc luôn",
  "haiz chán thật",
  "nhìn đú mất mệt",
  "sao đú",
  "cặc con",
  "ngu kìa",
  "chat mạnh đê",
  "hăng ee",
  "ơ ơ ơ",
  "sủa cháy đê",
  "sủa mạnh eei",
  "mày óc à con",
  "tao cho m chạy à",
  "con đĩ ngu sủa?",
  "mày chạy à con đĩ lồn",
  "sao chậm vậy",
  "nhanh lên cha xem nào",
  "cay cha à",
  "cố kháng cự cha à",
  "Nguyễn Gia Phúc Anh Bá Cmnr",
  "Cố Lên Sắp Ngầu = Chó Rồi",
  " Nghịch Tử Đang Cố Loạn Luân Mẹ Ruột Trước Mặt Cha ",
  "Thằng Nghịch Tử Đang Cố Phản Kháng Anh",
  "Có Lớn Đéo Có Khôn Phải Nhờ Cha Dậy Chữ Hiếu Và Chữ Trọng",
  "Thằng Lồn",
  "hăng đi con chó ngu ăn cứt 💩",
  "Địt Mẹ Sao Lại Vang Xin Anh Tha Vậy?",
  "Thằng Núi Nhìn Trong Phèn Làm Sao",
  "nào ngầu bằng anh?",
  "Cố Lên Đi Nào",
  "Chậm Thế",
  "Nhanh Lên Đi",
  "Nhìn Mày Phèn Vc",
  "sao lại cay anh hả",
  "mãi chưa bằng anh nhìn tội nghiệp vc",
  "Nghịch Tử Đang Cố Phản Kháng Cha",
  "địt mẹ thằng bất hiếu",
  "giết cha đụ mẹ",
  "cầm con cặc đụ lồn chó",
  "cặc nhỏ tới nổi chó tao khinh",
  "Nào Hết Ngu Vậy Nói Cha Nghe",
  "ơ thằng cặc đi đâu đây",
  "nhìn mày như mấy thằng đụ gái sì ke vậy",
  "bị lây hiv dẫn đến ngu",
  "nhìn mày ảo mà tao mệt dùm",
  "lên mxh cứ ảo war giúp gì cho mày được không",
  "nhìn mày như mấy đứa óc lồn lên mạng ảo mxh",
  "nhìn ngu chết đĩ mẹ tưởng mình hay à",
  "gõ nhanh lên tao xem nào",
   "nhanh lên tao xem", 
  "sao mày gõ chậm thế",
  "gõ ngu thế kia",
  "nhìn mày trong phèn vãi",
  "mãi chưa lớn",
  "mày bắc kì à sao ngu vậy",
  "con chó sủa cha nghe🐶",
  "sủa lớn lên cho cha nghe đi",
  "nhanh lên cha xem",
  "Ngu Như 🐮",
  "nhìn mày sôn như 1 con chó",
  "Nhìn mày tật đến đáng thương",
  "Sao mày hay đú vậy", 
  "ảo mxh là thói quen của con chó như mày à", 
  "nếu một mai gặp anh thì hãy out nhé",
  "xạo lồn trước mặt anh",
  "nhìn mày sủa tiếng chó nghe nhức đầu vc", 
  "sao vậy", 
  "thằng đĩ", 
    "sôn lên cha xem",
    "đụ mẹ mày đến chết",
    "thằng nghịch tử loạn luận mẹ ruột",
    "địt mẹ mày",
    "Mày Sống Như Lồn",
    "đéo để đức cho con cháu",
  "lên mạng cứ xàm lồn",
  "tưởng vậy là hay lắm à thằng ngu", 
  "ngu mà hay xạo lồn",
  "mày xàm lồn gì vậy",
    "địt mẹ thằng ngu",
    "cạn ngôn đến ngu",
  "sao lại yếu thế kia",
  "nhanh lên tao xem nào",
  "mày ngu mà",
   "thằng não cặc đang cố biện minh", 
  "Thằng lồn ơi",
    "sắp ngầu rồi cố lên",
    "thằng ngu sắp ngầu rồi",
    "mày óc mà thằng lồn",
      "nhanh lên tao xem nào",
      "mày chậm thế",
      "nhanh lên đi con chó",
      "thằng đĩ óc cặc cay cha",
      "sao mày nhảm vậy",
      "ớt cha à 🤣",
      "mày cay cmmnr",
      "óc chó ơi 🐶",
      "sủa cha nghe 🐶",
      "mẹ mày đang hấp hối kìa",
      "cha mày đang truy tìm mày kìa",
      "kiếm để chém thằng nghịch tử như mày",
      "loạn luân mẹ ruột à thằng nghịch tử",
      "địt mẹ đời mày như lồn á",
      "gặp anh là do mày ngu rồi 🤣👈",
      "sao gõ chậm",
      "nhanh lên tao xem",
      "chậm vậy thằng óc cặc",
      "nhanh lên cha xem",
      "muốn run lắm à",
      "sao tao thấy mày cứ sợ tao à",
      "nhìn cay đỏ dái",
      "không trêu nghịch tử nè",
      "nghịch tử sắp về méc mẹ á 🤣👈",
      "nghịch tử đang run sợ anh à",
      "sao khóc nói anh nghe",
      "chơi không có méc mẹ nè 🤣",
      "sợ thì out đi 🐶",
     "cố gắng làm cha cay đi em",
     "thằng nhóc bú lồn mẹ 🙄",
     "lên mạng xàm lồn với cha kìa",
     "ớt cha đỏ con cặc",
     "cần anh cho chó gãi dùm không",
    "mẹ mày đang phản kháng cha mà",
  "con mẹ mày đang quỳ lại tao kìa 😏",
    "tha cho thằng bất hiếu như mày",
    "ZN tao bá mà 💮🎭",
    "Hăng Hái Lên Nào Sao Chậm Vậy",
    "Ai cứu được mày vậy",
    "tag vào tao xem đi 🙄🙄",
    "con đĩ mẹ mày đang hấp hối kìa",
    "mày gà đúng không",
    "speed đi nào",
    "chậm vậy nhóc ác",
      "mày bại gõ mà thằng ngu",
      "mãi bại thôi thằng ngu à",
      "ửa với anh đừng có méc mẹ nhá 🤣🤣",
      "sợ mày đang khóc lắm 🤣",
      "gặp cha là mày xui lắm con",
      "cố thể hiện để hơn cha nè",
      "cố lên đi sắp giống con chó rồi 😏🤣",
      "cố chạy đi thằng nhóc",
      "sợ cha cmnr",
      "mày đang run sợ anh à 🤣",
      "thằng nghịch tử đừng cay anh nha 😝😜",
      "ớt cha à cay cmnr 😜🤣",
      "gõ nhanh lên thằng ngu",
      "thua tao là thế???",
      "nguyễn gia phúc anh làm mày sợ à",
      "nghịch tử đang cố cay cha 🤣",
      "nhanh lên xem nào ớ",
    "gõ nhanh lên xem nào",
    "chậm vậy mày gà à",
    "sao gõ chậm thế",
    "tao gõ bá cmnr",
    "mày óc cặc",
    "mày ngu lồn ớ 🐶",
    "con chó nghe lời cha quá",
    "mày gà mà ớ",
    "sao mày mãi gà thế",
    "nhanh lên tí được không?",
    "tao nhìn mày gõ tao buồn ngủ vc",
    "mày mãi gà mà thằng ngu",
    "mày gà vậy",
    "gõ đi thằng óc", 
    "nhanh lên đi",
    "lên trời cao không em",
    "đi chết kìa thằng dái",
    "con mẹ mày ngu à",
    "gà + óc = mày",
    "công nhận mày ngu vc",
    "cố sồn như chó à",
    "sao bằng anh được vậy hả cu",
    " mày mãi gà ớ",
    "nhìn mày tật đến đáng thương",
    "mày óc dái mà",
    "vc đụ mẹ ruột à",
    "thằng nghịch tử ổn không???",
    "nghịch thiên là cha mà ",
    "ngày tử của mày á con chó", 
    "đang cay anh đúnh không",
  "rất ớt cha cmmnr",
  "cay đến đỏ cặc à",
  "cha cho mày sồn à",
  "à quên mày sv sao nghe hiểu",
  "thằng cứt dái bò",
    "óc lợn ngu như bò ",
     "cặc nhỏ xíu",
     "chị mày bị tao đụ đến vang xin nè ",
     "mày thấy tao tài không ớ ",
   "bị tao đụ đến khóc rồi ",
     "vì xin tha cho mày á ",
     "thằng ngu à ",
    "mếu cha cmmnr",
    "ZN Bá Vc",
    "ZN Anh Chuyên Trị Mấy Thằng Ngu Như Mày",
    "Gà Mà Hay Sủa à 🤣🤣",
    "tật nói chuyện kiểu",
       "Sủa Mau Lên🤣",
  "bố xin đái vào não tật mày nhé con chó",
  "Đĩ Má Mày Die",
  "sủa mạnh mẽ lên con lgbt ngu lồn",
  "mày hăng hái lên tí đc k",
  "Óc Chó🤭?",
  "sủa kìa",
  "mày biết sợ rồi à 🤣🤣?",
  "tao nói hồi sợ mày tự ái :(",
  "sợ mày bị tao sút đến die",
  "mày cố nữa đi 😂?",
  "clm 🤣?",
  "âm binh xuất trận à",
  "sát thương = 0 à",
  "Đã ngu còn thích tỏ ra mình có trình hả cn thú ngu êy",
  "Bởi vì mày làm gì có trình ?",
  "Thể hiện mình có trình đi con chó ngu ngục ơi ",
  "Sao mày sống mất dạy quá vậy bame mày khờ mà mày còn lười!",
  "Sủa hăng hái lên sao dị đú đa đú đỡn xạo lồn tập đú mxh ",
  "Lgbt xuất trận hả hay sao 🤔?",
  "Đừng cay cú cha mà hóa rồ lên làm nét ",
  "Nhìn lũ ngu dồn cha trong vô vọng kìa 😂",
  "Ráng đi sắp win r đó lũ đú êy",
  "Gần quin rồi ráng thêm sí nữa đi",
  "Đừng rụng nhé lũ ngu",
  "Trận này anh win rõ mà sao cưng chối ăng ẳng thế",
  "Khi nào con hết xàm lồn vậy?",
  "Sao con đú quá vậy con thú êy",
  "Alo con còn sống kh đó",
  "Hay bị hành quá nên sinh ra hoang tưởng ",
  "Mày sủa hăng hái lên cn thú đú eye",
  "Chậm chạp như rùa bò v",
  "Hăngg máu lên chứ yếu kém quá",
  "Gà mà hay xạo lồn quá vậy",
  "Cưng sủa lên đi sao im r ",
  "Cha cho im chưa hả cn thú ngu êy🤣",
  "Thấy cha là xách giò chạy hả",
  "Câm rồi à chán thế",
  "Mày nín r hả",
  "Sao nín r vậy",
  "Hay bị mẹ gank rồi",
  "Yếu kém quá cn thú ơi",
  "Hay đuối rồi jar",
  "Đuối r thì kêu cha cha tha cho",
  "Sao pải cuốn cuồng lên thế🤣",
  "Ai làm gì mà mếu r v",
  "Cay cú kh làm đc gì à",
  "Mếu máo rõ mà rồi sao nữa ht ngôn à ",
  "Yếu kém v thú đú nhảm lồn đú ửa kiểu",
  "Hay bị hành quá nên núp r",
  "Sao v mặt căng v cay cha rồi hả 🤨🌶?",
  "Cay cha rõ mà sao xạo lồn hả",
  "Nhìn mày gõ như đống tro tàn cốt mã nhà mày để lại cho mày vậy á",
  "Không được cay anh quá mà làm liều nghe chưa!",
  "Đừng bị anh chửi nhiều quá mà tự ái nhảy lầu tự tử nhé",
  "Đừng có lên mạng xã hội tạo nét mà bị anh hành là mếu máo đi cầu cứu ngay",
  "Khi nào có trình r đọ với anh chứ trình không có mà sủa hăng ghê ta ",
  "Cưng xạo lồn chứ làm gì có trình",
  "Rồi sao nữa",
  "Con điếm phò mã bị cha mày cầm cái cây chà bồn cầu cha chà nát lồn mày nè",
  "Con thú ngu dốt bị cha mày hành cho đầu óc quay cuồng r à",
  "Sao cay hả cay r làm được gì không hay chỉ được ngồi gõ nhảm bển 🌶",
  "Cay mếu máo sao khóc rồi",
  "Khóc r hả thương vậy",
  "Thương cho con thú cay anh mà không làm được gì",
  "Sao cho cầu cứu mà cầu cứu xog sao kh ai dám dô giúp ht vậy",
  "Sống chi bần hèn quá v",
  "Sao con đú mà con xạo lồn hả cn thú ngu êy",
  "Cha mày chuyên hành lũ đú mà",
  "Con sủa hăng máu lên ",
  "Câm là cha mày gọi hồn mày như gọi đò",
  "Con sơ hở là xạo lồn bịa chuyện ai xem",
  "Nhìn con dị hợm quá vậy?",
  "Con kiếp trước chắc sống phế lắm nhỉ",
  "Qua kiếp này làm lại từ đầu mà sao ngu quá v",
  "Cn thú cầm cái phím tắt ôm trong tuyệt vọng hả",
  "Đú sao lại được hả cn ngồi ôm phím gõ dăm ba mấy cái ngôn xưa lắc xưa lơ ",
  "Ai cứu mày được quả này",
  "Cầu cứu lẹ đi🤣",
  "Cha hóng nãy giờ nè🤣",
  "Mày mà câm là cha mày win rõ nhé",
  "Cha mày hóa thân thành hắc bạch vô thường cha mày bắt hồn đĩ mẹ mày xuống chầu diêm vương",
  "Con chó mày hăng hái lên xem nào",
  "Hay bị cha mày bón cho 1 kí hành dô mõm nên không dám sủa nữa",
  "cái thứ con người mà não còn không có mà đòi đọ với ai🤣",
  "Nhìn mặt mày như con tinh tinh đầu thai chuyển kiếp thành con người v🤣",
  "Nhìn mặt mày là thấy 2 chữ phèn ngu😗",
  "Đã nghèo đã phèn đã ngu đã dốt mà đòi hơn ai",
  "Bản thân mình không làm được cho mình thì làm được cho ai",
  "Sống như 1 con chó ngu dốt như lũ phèn ói chợ búa cầm dao múa kiếm",
  "Sủa hăng hái lên chứ yếu kém quá cha mày hăng không nổi😉!",
  "Gõ phím tắt để làm nét ai xem",
  "Mày đi cầu cứu ai hả!?",
  "Tao đố đứa nào dám dô cứu mày đấy",
  "Đã ngu còn hay tạo nét",
  "Cha mày tới là lũ ngu cũm pải dè chừng",
  "Đã ngu còn đú thì phế mẹ đi",
  "Cha đấng mxh mà🤔!",
  "Cưng ganh tị với anh hả?",
  "Cưng hăng hái với ai?",
  "Sao con đuối rồi hả?",
  "Chỉ được vậy thôi hả!",
  "Còn chiêu nào không tung ra đi",
  "Chứ thấy mấy cái chiêu trò phèn của mày đi trong ruột mày từ 7 kiếp r ",
  "Bị cha mày hành nhiều quá nên sính ra hoa tưởng hả 🤨?!",
  "Con sống ngu mà con hay tạo nét quá v cn thú ngu êy",
  "Con thú ngu bị cha mày hành nhìu quá nên không dám sủa nữa à",
  "Sao vậy yếu kém vậy hay đuối r hả đĩ gà mờ",
  "Cha mày tới là lũ ngu cũm pải rén mà thôi", 
  "Hăng lên xíu được không dọ",
  "Nín hết rồi hả sao không hăng như ban đầu đê",
  "Sao mấy cn thú đi theo bầy đàn bị cha mày hành tới mức mà pải núp hết rồi dị",
  "Não mày bị chèn tinh trùng của thằng cha mày trổng hả?",
  "Não tàn đến mức pải đi xin tha hả?",
  "Não mày chứa toàn cứt của con chó nhà mày à",
  "Sao mày không hăng hái nữa",
  "Hay rớt rồi hả",
  "Sao câm nín rồi 😑",
  "Sủa hăng hái máu chiến lên nào",
  "Yếu kém v con thú đú ngu êy",
  "Sủa sao cho nghe lọt lỗ tai",
  "Cha tới nè nhú lên diện kiến cha lẹ",
  "Bame mày quỳ lạy kêu anh xin tha mà",
  "Cốt cách như buồi gõ xàm gõ điên",
  "Gõ sao lại tụi anh được hả lũ đú ",
  "Đã ngu còn thích sỉ diện",
  "Chó ngoan cục cưng hãy về với chủ đừng cắn bậy",
  "Sống sang lên cho nết thanh tịnh",
  "Sống dơ sồng hèn muôn đời bết",
  "Còn sống thì nhú lên đú tiếp cho tụi anh chiêm ngưỡng",
  "Tàn tạ từ nhân cách đến não bộ",
  "Sống cho cuộc đời có tâm và có tầm",
  "Ngu thì đừng phán vs ai nhé cn chó ghẻ ",
  "Nghe 1 thời giảng sanh của cha mà tích đức",
  "Sống như con chó ngu dốt đầu đường xó chợ",
  "Ngồi xuống cha giảng đạo cho nghe nè",
  "Nghèo bần hèn bị cha mày đứng trên đạp đầu lũ đú chúng mày cha đi lên ",
  "Cay mếu máo cha mà chả làm được gì hả",
  "Không được quay qua méc mẹ nghe chưa",
  "Đã ngu còn thích thể hiện hả thk nhóc",
  "Khi nào đủ trình r so với anh nghe chưa",
  "Thân phận nghèo hèn đú ai xem ",
  "Đú má mày tới tháng xịt nước máu kinh cho thk cha mày uống",
  "Khi nào con có đủ tầm ảnh hưởng lên đứng với cha ",
  "ê wavy giả bộ ngừng đi",
  "Gõ ngôn lặp đi lặp lại ngôn 1 màu thì đừng gõ",
  "Thứ yêu nghiệt xuống hạn nhân sanh",
  "Sủa dơ cha mày cầm cái chổi nhét dô lồn m nè",
  "Thứ súc sinh muốn tiến hóa thành người",
  "Mày ngưng là má mày đột tử tới",
  "Thú đú như mày làm cha bùn cười quá ",
  "Khi nào có trình đú với anh nha",
  "Sao chậm quá vậy?😂",
  "Sủa hăng hái mạnh mẽ lên",
  "Cốt cách thiên nga tâm hồn quỷ dữ 😈",
  "sủa mau lên con chó🤣🤣",
  "con đĩ cave lộ lồn cay kiểu🤣🤣",
  "lũ ngu đòi đọ bot anh🤣👉",
  "kkk🤣🤣",
  "con đĩ cave show lồn show dú kiểu😜",
  "mày sợ anh à con đĩ😏?",
  "xạo à clm cuoii😏?",
  "sao m xạo da👉",
"cố đeee🤭",
"sồn hăng lên em🥺",
  "lên nhây cái em êi",
"m lết mặt thú m lên nhây đê",
"sồn như chó cắn v",
"nhanh đi thg óc heo",
"não tép à",
"sao vậy ",
"chửi nhau hăng đi ",
"làm tí nhây",
"cố gắng xíuuuu",
"đc kh đó",
"thấy m chậm vãi l",
"cần anh chiêu mộ cho m ko đĩ",
"đáp ngôn nhanh hơn tý đc k tk ngu xuẩn🌬",
"m ớt cha hả🌶",
"m sợ cha đến v à",
"đụ má thg lồn mồ côi",
"cãi cùn lmj",
"m bại à",
"mày còn trò gì hay k",
"nhai lmjz tr",
"kh đc méc mẹ nè",
"câm à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"sao m yếu v😔",
"cố tí nữa👉",
"sao kìa chậm à🙃",
"hăng hái lên tí chứ😤",
"tới sáng đi em ei=))",
"cố gắng tí eii🤑",
"k đc à:))",
"con eii cố de😗",
"sao m câm kì:))",
"gà j🤭",
"tnh gà=))",
"m gà mà🤨",
"dk à:)?",
"đúng mà ?",
"cãi à :))",
"mày còn gì khác hơn không :))",
"học lỏm kìa🤣",
"cố tí e ?",
"mếu à😭",
"sao mếu kìa:))",
"tao đã cho m mếu đâu :))",
"va lẹ lên chậm v😏?",
"sao kìa",
"từ bỏ r à",
"bị bạn bè bỏ rơi à 😏?",
"mạnh mẽ tí đi nà",
"cố đê con chó ăn cứt:))?",
":)))",
"sợ tao kìa🤣",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố eiii",
"hăng tiếp đi",
"tới sáng k em",
"ko tới sáng à",
"chán v",
"m gà vậy :))",
"sao ngu dậy con:))",
"coi tụi nó dồn ngu kìa",
"sao mày ngu dậy:))?",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới nhiêu đó đã đuối r à:))?",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận ae eii",
"thg cặc giết cha mắng mẹ",
"sủa mạnh đê",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à🤣🤣",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"sao lại chạy vậy😏?",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"sủa cháy đê",
"sủa mạnh eei",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi à",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi",
  "bị chửi nên không phản kháng à",
  "con cave và tk cu bé hợp nhề😏",
  "con bede không phản kháng được à",
  "con bede sợ anh rồi:)",
  "chạy về mách mẹ à con bede",
  "chạy về trốn dô cái lồn mẹ mày đi?",
  "1 đứa bú lồn mẹ",
  "1 đứa bú cu cha",
  "bất hiếu cmnr:))",
  "mày làm gì để anh sợ đi:))",
  "mày có tý sát thương nào ko",
  "con đĩ mẹ mày ăn cứt cố đi",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm",
  "lũ cave cay cha cmnr",
  "cay anh  r à lũ đú",
  "sợ anh  à",
  "anh  win m mà:)))",
  "win nha clm bede🤣🤣",
  "sủa đi",
"cố lên con",
"sồn hăng lên em",
"sao m yếu v ",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em=))",
"cố gắng tí con chó dốt=))",
"k đc à",
"con chó ngu cố đê",
"sao m câm kìa",
"gà j",
"mày sợ anh à =))",
"m gà mà",
"mày ngu rõ mà",
"đúng mà",
"cãi à",
"mày còn gì khác k",
"học lỏm kìa",
"cố tí em",
"mếu à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"va lẹ đi con dốt",
"sao kìa",
"từ bỏ r à",
"mạnh mẽ tí đi con đĩ",
"cố lên con chó ngu",
"=)) cay tao à con đĩ",
"sợ tao à",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố lên chó dốt",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"m gà mà",
"log acc thay phiên à",
"coi tụi nó dồn ngu kìa",
"sợ tao à con chó đần",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới 5p đã câm r",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
   "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi sao",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi🥺?",
  "bị chửi nên không phản kháng à😀?",
  "con cave và tk cu bé hợp nhề😏👉",
  "2 con bede không phản kháng được à😋",
  "2 con bede sợ anh rồi:))🙃",
  "chạy về mách mẹ à 2 con bede😗?",
  "chạy về trốn dô cái lồn mẹ mày đi😍?",
  "1 đứa bú lồn mẹ😎?",
  "1 đứa bú cu cha😎?",
  "bất hiếu cmnr:))😜",
  "mày làm gì để anh sợ đi:))🤣?",
  "mày có tý sát thương nào ko😂?",
  "con đĩ mẹ mày ăn cứt cố đi🤣?",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm🤣",
  "lũ cave cay cha cmnr😑",
  "cay cha r à lũ đú😅",
  "sợ anh tao rồi à😗",
  "anh  win m mà:)))",
  "win nha clm bede🤣🤣",
   "con eii",
"cố đeee",
"sồn hăng lên em",
"sao m yếu v",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em eii",
"cố gắng tí eii",
"k đc à",
"con eii cố de",
"sao m câm kìa",
"gà j",
"tnh gà",
"m gà mà",
"dk à",
"đúng mà",
"cãi à",
"mày còn gì khác k",
"học lỏm kìa",
"cố tí em",
"mếu à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"va lẹ eii",
"sao kìa",
"từ bỏ r à",
"mạnh mẽ tí đi nà",
"cố eii",
":)))",
"sợ tao à",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố eiii",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"m gà mà",
"log acc thay phiên à",
"coi tụi nó dồn ngu kìa",
"ae ơiii",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới 5p đã câm r",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận ae eii",
"thg cặc giết cha mắng mẹ",
"sủa mạnh eii",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"sủa cháy đê",
"sủa mạnh eei",
"hăng lên đeeee",
"sồn hăng lên em",
"thấy m yếu ",
"cố tí nha",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em eii",
"cố gắng tí nữa sắp win r á",
"kh đc à hay sao v",
"con eii cố lên",
"sao m câm kìa",
      "sủa đi",
      "cố lên con",
      "sồn hăng lên em",
      "sao m yếu v ",
      "cố tí nữa",
      "sao kìa chậm à",
      "hăng hái lên tí chứ",
      "tới sáng đi em=))",
      "cố gắng tí con chó dốt=))",
      "k đc à",
      "con chó ngu cố đê",
      "sao m câm kìa",
      "gà j",
      "mày sợ anh à =))",
      "m gà mà",
      "mày ngu rõ mà",
      "đúng mà",
      "cãi à",
      "mày còn gì khác k",
      "học lỏm kìa",
      "cố tí em",
      "mếu à",
      "sao mếu kìa",
      "tao đã cho m mếu đâu",
      "va lẹ đi con dốt",
      "sao kìa",
      "từ bỏ r à",
      "mạnh mẽ tí đi con đĩ",
      "cố lên con chó ngu",
      "=)) cay tao à con đĩ",
      "sợ tao à",
      "sao sợ tao kìa",
      "cay lắm phải kh",
      "ớt rồi kìa em",
      "mày còn chối à",
      "làm tí đê",
      "mới đó đã mệt r kìa",
      "sao gà mà sồn v",
      "sồn như lúc đầu cho tao",
      "sao à",
      "ai cho m nhai",
      "cay lắm r",
      "từ bỏ đi em",
      "mày nghĩ mày làm t cay đc à",
      "có đâu",
      "tao đang hành m mà",
      "bịa à",
      "cay :)))))",
      "cố lên chó dốt",
      "hăng tiếp đi",
      "tới sáng k em",
      "k tới sáng à",
      "chán v",
      "m gà mà",
      "log acc thay phiên à",
      "coi tụi nó dồn ngu kìa",
      "sợ tao à con chó đần",
      "lại win à",
      "lại win r",
      "lũ cặc cay tao lắm🤣🤣",
      "cố lên đê",
      "sao mới 5p đã câm r",
      "yếu đến thế à",
      "sao kìa",
      "khóc kìa",
      "cầu cứu lẹ ei",
      "ai cứu đc m à :))",
      "tao bá mà",
      "sao m gà thế",
      "hăng lẹ cho tao",
      "con chó eiii🤣",
      "ổn k em",
      "kh ổn r à",
      "mày óc à con chó bẻm=))",
      "mẹ mày ngu à",
      "bú cặc cha m k em",
      "thg giả gái :))",
      "coi nó ngu kìa ae",
      "con chó này giả ngu à",
      "m ổn k",
      "mồ côi kìa",
      "sao v sợ r à",
      "cố gắng tí em",
      "cay cú lắm r",
      "đấy đấy bắt đầu",
      "chảy nước đái bò r à em",
      "sao kìa đừng run",
      "mày run à:))",
      "thg dái lở",
      "cay mẹ m lắm",
      "lgbt xuất trận à con đĩ",
      "thg cặc giết cha mắng mẹ",
      "sủa mạnh eii",
      "mày chết r à:))",
      "sao chết kìa",
      "bị t hành nên muốn chết à",
      "con lồn ngu=))",
      "sao kìa",
      "mạnh lên kìa",
      "yếu sinh lý à",
      "sủa đê",
      "cay à",
      "hăng đê",
      "gà kìa ae",
      "akakaa",
      "óc chó kìa",
      "🤣🤣🤣",
      "ổn không🤣🤣",
      "bất ổn à",
      "ơ kìaaa",
      "hăng hái đê",
      "chạy à 🤣🤣",
      "tởn à",
      "kkkk",
      "mày dốt à",
      "cặc ngu",
      "cháy đê",
      "chat hăng lên",
      "cố lên",
      "mồ côi cay",
      "cay à",
      "cn chó ngu",
      "óc cặc kìa",
      "đĩ đú:))",
      "đú kìa",
      "cùn v",
      "r x",
      "hhhhh",
      "kkakak",
      "sao đú",
      "cặc con",
      "ngu kìa",
      "chat mạnh đê",
      "hăng ee",
      "ơ ơ ơ",
      "sủa cháy đê",
      "sủa mạnh eei",
      "mày óc à con",
      "tao cho m chạy à",
      "con đĩ ngu sủa?",
      "mày chạy à con đĩ lồn",
    ]
  }
};



let index = 0;
let isStopped = false;

export function Running( {
  message,extra
}) {
  const {list} = extra;
  const args = message.body.split(" ").slice(1);
  if (args[0] === "stop") {
    isStopped = true;
    message.send("alo");
    return;
  }

  if (isStopped) {
    isStopped = false;
  }

  const sendText = () => {
    message.send(list[index]);
    index = (index + 1) % list.length;
    if (!isStopped) {
      setTimeout(sendText, 2000);
    }
  };
  sendText();
}

export default {
  config,
  Running
};
